/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TaskManagerWorkArea;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.RescueNetEnterprise;
import model.Enterprise.VolunteerEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.DriverOrg;
import model.Organization.RequestCollectOrg;
import model.Organization.RequestEntertainOrg;
import model.Organization.VolunteerOrg;
import model.Role.Deliver;
import model.WorkQueue.WorkQueue;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestDelivery;
import model.WorkQueue.WorkRequestFoodItem;
import model.WorkQueue.WorkRequestNeeds;

/**
 *
 * @author sylvia
 */
public class TaskManagerWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form CoordinatorWorkPanel
     */
    VolunteerEnterprise volunteerEnterprise;
    VolunteerOrg volunteerOrg;
    NetWork netWork;
    JPanel workArea;
    public TaskManagerWorkPanel(JPanel workArea, UserAccount account, BasicOrganization organization, BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.volunteerEnterprise = (VolunteerEnterprise) enterprise;
        this.volunteerOrg = (VolunteerOrg) organization;
        this.netWork = netWork;
        initComponents();
        populateTableDriver();
        populateTableTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDrivers = new javax.swing.JTable();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUnassignedTasks = new javax.swing.JTable();
        btnAssignTask = new javax.swing.JButton();
        btnAssignTask1 = new javax.swing.JButton();
        btnAssignTask2 = new javax.swing.JButton();

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Task Manager - Task Assignment");

        tbDrivers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Driver ID", "Name", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDrivers);

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel1.setText("Available Drivers ");

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseLabel2.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel2.setText("Shelter Request Tasks ");

        tbUnassignedTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Food ID", "Food Name", "Quantity", "From", "To", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbUnassignedTasks);

        btnAssignTask.setText("Assign Task");
        btnAssignTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTaskActionPerformed(evt);
            }
        });

        btnAssignTask1.setText("Refresh undo");
        btnAssignTask1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTask1ActionPerformed(evt);
            }
        });

        btnAssignTask2.setText("View All");
        btnAssignTask2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTask2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btnAssignTask))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(enterpriseLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(enterpriseLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(95, 95, 95)
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btnAssignTask1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignTask2)
                .addGap(174, 174, 174))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterpriseLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignTask1)
                    .addComponent(btnAssignTask2))
                .addGap(20, 20, 20)
                .addComponent(enterpriseLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAssignTask)
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(253, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnAssignTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTaskActionPerformed
        // TODO add your handling code here:
        //get task and driver with tables
        int TaskRow = tbUnassignedTasks.getSelectedRow();
        int DriverRow = tbDrivers.getSelectedRow();
        if (TaskRow < 0 || DriverRow<0) {
            JOptionPane.showMessageDialog(null, "Please select a Task first.");
            return;
        }
        WorkRequestDelivery task = (WorkRequestDelivery) tbUnassignedTasks.getValueAt(TaskRow, 5);
        UserAccount usDriver = (UserAccount) tbDrivers.getValueAt(DriverRow, 1);
        
        // check task status
        if(!task.getTaskStatus().equals("UnPick")){
            JOptionPane.showMessageDialog(null, "Please select an unPicked Task.");
            return;
        }
        
        task.setDeliver(usDriver);
        JOptionPane.showMessageDialog(null, "Task set successfully.");      
        task.setTaskStatus("picked");
        
    }//GEN-LAST:event_btnAssignTaskActionPerformed

    private void btnAssignTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTask1ActionPerformed
        // TODO add your handling code here:
        populateTableTaskUndo();
    }//GEN-LAST:event_btnAssignTask1ActionPerformed

    private void btnAssignTask2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTask2ActionPerformed
        // TODO add your handling code here:
        populateTableTask();
    }//GEN-LAST:event_btnAssignTask2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAssignTask;
    private javax.swing.JButton btnAssignTask1;
    private javax.swing.JButton btnAssignTask2;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbDrivers;
    private javax.swing.JTable tbUnassignedTasks;
    // End of variables declaration//GEN-END:variables

    
    ////////////////function ///////////////////
    // populizeTable
    public void populateTableTask(){
        DefaultTableModel model = (DefaultTableModel) tbUnassignedTasks.getModel();
        model.setRowCount(0);
        ArrayList<BasicEnterprise> enterprises = netWork.getEnterpriseDirectory().getEnterprises();
        // 拿到type为 rescueNet的公司
        //ArrayList<RescueNetEnterprise> rescueNetEnterprises = new ArrayList<>();
        for(BasicEnterprise enterprise: enterprises){
            if(enterprise.getEnterpriseType().getValue().equals("RescueNetEnterprise")){
                RescueNetEnterprise en = (RescueNetEnterprise)enterprise;
                RequestEntertainOrg org =en.getRequestEntertainOrg();
                for (WorkRequest wd : org.getWorkQueue().getWorkRequestList()) {
                    WorkRequestDelivery wrd = (WorkRequestDelivery) wd;
                    Object row[] = new Object[6];
                    row[0] = "undo";
                    row[1] = wrd.getFoodItem().getFoodName();
                    row[2] = wrd.getFoodItem().getNumber();
                    row[3] = wrd.getFoodItem().getFoodIncOrg().getAddress();
                    row[4] = wrd.getReceiver().getAddress();
                    row[5] = wrd.getStatus();
                    model.addRow(row);            
                } 
            }
        }
    }
    
    //populate Task Undo
    public void populateTableTaskUndo(){
        DefaultTableModel model = (DefaultTableModel) tbUnassignedTasks.getModel();
        model.setRowCount(0);
        ArrayList<BasicEnterprise> enterprises = netWork.getEnterpriseDirectory().getEnterprises();
        // 拿到type为 rescueNet的公司
        //ArrayList<RescueNetEnterprise> rescueNetEnterprises = new ArrayList<>();
        for(BasicEnterprise enterprise: enterprises){
            if(enterprise.getEnterpriseType().getValue().equals("RescueNetEnterprise")){
                RescueNetEnterprise en = (RescueNetEnterprise)enterprise;
                RequestEntertainOrg org =en.getRequestEntertainOrg();
                for (WorkRequest wd : org.getWorkQueue().getWorkRequestList()) {
                    WorkRequestDelivery wrd = (WorkRequestDelivery) wd;
                    if(wrd.getStatus().equals("unpick")){
                        Object row[] = new Object[6];
                        row[0] = "undo";
                        row[1] = wrd.getFoodItem().getFoodName();
                        row[2] = wrd.getFoodItem().getNumber();
                        row[3] = wrd.getFoodItem().getFoodIncOrg().getAddress();
                        row[4] = wrd.getReceiver().getAddress();
                        row[5] = wrd;
                        model.addRow(row);
                    }            
                } 
            }
        }
    }
    
    public void populateTableDriver(){
        DefaultTableModel model = (DefaultTableModel) tbDrivers.getModel();
        model.setRowCount(0);
        //拿到driverOrg
        ArrayList<BasicEnterprise> enterprises = netWork.getEnterpriseDirectory().getEnterprises();
        for(BasicEnterprise enterprise: enterprises){
            if(enterprise.getEnterpriseType().getValue().equals("Volunteer")){
                VolunteerEnterprise en = (VolunteerEnterprise)enterprise;
                for(BasicOrganization org: en.getOrganizationDirectory().getOrganizationList()){
                    if(org instanceof DriverOrg driverOrg){
                        for (UserAccount account : driverOrg.getEmployees()) {
                            Object row[] = new Object[6];
                            row[0] = "undo";
                            row[1] = account;
                            Deliver deliver = (Deliver) account.getRole();
                            row[2] = deliver.getStatus();
                            model.addRow(row);            
                        } 
                    }
                }  
            }
        }
        
    }
}
