/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ReportAnalystWorkArea;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Box;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account.UserAccount;
import model.FoodItem.FoodItem;
import model.FoodShelterSystem.FoodShelterSystem;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestFoodItem;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import ui.AdminWorkArea.AdminStartPoint;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.image.BufferedImage;
import java.io.FileOutputStream;
import model.Enterprise.BasicEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.WorkQueue.DeliveryTask;
import model.WorkQueue.WorkRequestDelivery;


/**
 *
 * @author yuewu
 */
public class SummaryMetricsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SummaryMetricsPanel
     */
    FoodShelterSystem foodShelterSystem;
    JPanel workArea;
    UserAccount account;
    public SummaryMetricsPanel(JPanel workArea,FoodShelterSystem foodShelterSystem,UserAccount ua) {
        this.foodShelterSystem = foodShelterSystem;
        this.workArea = workArea;
        this.account = ua;
        initComponents();

        btnExport.addActionListener(e -> exportReportAsPDF());



        loadSummaryMetrics();

        showChart();
        beautify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalDonated = new javax.swing.JLabel();
        lblEnergySaved = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnExport = new javax.swing.JButton();

        lblTotalStored = new javax.swing.JLabel();


        chartContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SummaryMetrics");

        lblTotalDonated.setText("Total Food Donated: ");

        lblEnergySaved.setText("Estimated Energy Saved:");

        BtnBack.setText("<<  Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });


        btnExport.setText("Export Report 📤");

        lblTotalStored.setText("Total Food Stored: ");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(BtnBack)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalDonated)

                            .addComponent(lblEnergySaved)
                            .addComponent(lblTotalStored)))

                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(chartContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BtnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport)
                .addGap(8, 8, 8)
                .addComponent(lblTotalDonated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addComponent(lblTotalStored)
                .addGap(9, 9, 9)
                .addComponent(lblEnergySaved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        AdminStartPoint adminStartPoint = new AdminStartPoint(workArea, account, foodShelterSystem);
        workArea.add("AdminStartPoint",adminStartPoint);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "AdminStartPoint");
    }//GEN-LAST:event_BtnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton btnExport;
    private javax.swing.JPanel chartContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEnergySaved;
    private javax.swing.JLabel lblTotalDonated;
    private javax.swing.JLabel lblTotalStored;
    // End of variables declaration//GEN-END:variables

    private void showChart() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        int donated = 0;
        int stored = 0;

         for (NetWork net : foodShelterSystem.getNetworkList()) {
        for (BasicEnterprise be : net.getEnterpriseDirectory().getEnterprises()) {
            for (BasicOrganization org : be.getOrganizationDirectory().getOrganizationList()) {
                for (WorkRequest wr : org.getWorkQueue().getWorkRequestList()) {

                    // Stored Food: Food items with usingStatus "stored"
                    // This includes all items that have been approved by food check
                    if (wr instanceof WorkRequestFoodItem && !(wr instanceof WorkRequestDelivery) && !(wr instanceof DeliveryTask)) {
                        WorkRequestFoodItem foodReq = (WorkRequestFoodItem) wr;
                        FoodItem item = foodReq.getFoodItem();
                        if (item != null && "stored".equalsIgnoreCase(item.getUsingStatus())) {
                            stored += item.getNumber();
                            System.out.println("Adding to stored: " + item.getFoodName() + " - " + item.getNumber());
                        }
                    }

                    // Donated Food: delivery requests with taskStatus "Delivered"
                    if (wr instanceof WorkRequestDelivery) {
                        WorkRequestDelivery deliveryReq = (WorkRequestDelivery) wr;
                        if (deliveryReq.getFoodItem() != null 
                            && "Delivered".equalsIgnoreCase(deliveryReq.getTaskStatus())) {
                            donated += deliveryReq.getFoodItem().getNumber();
                            System.out.println("Adding to donated (delivery): " + 
                                deliveryReq.getFoodItem().getFoodName() + " - " + 
                                deliveryReq.getFoodItem().getNumber());
                        }
                    } else if (wr instanceof DeliveryTask) {
                        DeliveryTask deliveryTask = (DeliveryTask) wr;
                        if ("Delivered".equalsIgnoreCase(deliveryTask.getStatus())) {
                            donated += deliveryTask.getQuantity();
                            System.out.println("Adding to donated (task): " + 
                                (deliveryTask.getFoodItem() != null ? 
                                deliveryTask.getFoodItem().getFoodName() : "Unknown") + 
                                " - " + deliveryTask.getQuantity());
                        }
                    }
                }
            }
        }
    }
        
            for (NetWork net : foodShelterSystem.getNetworkList()) {
        if (net.getWarehouseList() != null) {
            for (WorkRequest wr : net.getWarehouseList().getWorkRequestList()) {
                if (wr instanceof WorkRequestFoodItem && !(wr instanceof WorkRequestDelivery)) {
                    WorkRequestFoodItem foodReq = (WorkRequestFoodItem) wr;
                    FoodItem item = foodReq.getFoodItem();
                    if (item != null && "stored".equalsIgnoreCase(item.getUsingStatus())) {
                        stored += item.getNumber();
                        System.out.println("Adding to stored from warehouse: " + 
                            item.getFoodName() + " - " + item.getNumber());
                    }
                }
            }
        }
    }
              
        // pie chart
        dataset.setValue("🍽 Donated", donated/2);
        dataset.setValue("🥫 Stored", stored/2);

        JFreeChart pieChart = ChartFactory.createPieChart(
                "Food Usage Distribution",
                dataset,
                true,
                true,
                false);

        PiePlot plot = (PiePlot) pieChart.getPlot();
        plot.setSectionPaint("🍽 Donated", new Color(139, 195, 74)); // 
        plot.setSectionPaint("🥫 Stored", new Color(255, 202, 40)); // 
       
        plot.setCircular(true);
        plot.setOutlineVisible(false);
        plot.setShadowPaint(null);
        
        plot.setLabelFont(new Font("Segoe UI", Font.BOLD, 13));
        plot.setLabelBackgroundPaint(new Color(245, 242, 250));
        plot.setLabelOutlinePaint(null);
        plot.setLabelShadowPaint(null);
        
        plot.setBackgroundPaint(new Color(245, 242, 250));
        pieChart.setBackgroundPaint(new Color(245, 242, 250));
        pieChart.setTitle(new org.jfree.chart.title.TextTitle(
                "Food Usage Distribution", new Font("Segoe UI", Font.BOLD, 16)));

        ChartPanel piePanel = new ChartPanel(pieChart);
        Dimension fixedSize = new Dimension(280, 240);
        piePanel.setPreferredSize(fixedSize);
        piePanel.setBackground(new Color(245, 242, 250));

//        piePanel.setPreferredSize(fixedSize);
//        piePanel.setMaximumSize(fixedSize);
//        piePanel.setMinimumSize(fixedSize);
//        piePanel.setSize(fixedSize);

        // bar chart
        
        Color donatedBarColor = new Color(0, 184, 148); // Vibrant teal
        Color barChartBackgroundColor = new Color(248, 249, 250);

        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        barDataset.setValue(donated/2, "Food", "🍽 Donated");
        barDataset.setValue(stored/2, "Food", "🥫 Stored");

        JFreeChart barChart = ChartFactory.createBarChart(
                "Donation Summary",
                "Status",
                "Quantity",
                barDataset,
                PlotOrientation.VERTICAL,
                false, true, false);

        barChart.setBackgroundPaint(barChartBackgroundColor);
        barChart.setTitle(new org.jfree.chart.title.TextTitle(
                "Donation Summary", new Font("Segoe UI", Font.BOLD, 16)));

        var barPlot = barChart.getCategoryPlot();
        barPlot.setBackgroundPaint(barChartBackgroundColor);
        barPlot.setOutlineVisible(false);
        barPlot.setRangeGridlinePaint(new Color(230, 230, 230)); // Lighter grid lines

// Updated modern colors for bars - just change the series paint
        barPlot.getRenderer().setSeriesPaint(0, donatedBarColor); // Vibrant teal for donated
        barPlot.getRenderer().setDefaultItemLabelsVisible(true);
        barPlot.getRenderer().setDefaultItemLabelFont(new Font("Segoe UI", Font.PLAIN, 12));

// Set nicer fonts for the axes
        Font axisFont = new Font("Segoe UI", Font.BOLD, 13);
        Font tickFont = new Font("Segoe UI", Font.PLAIN, 12);
        barPlot.getDomainAxis().setLabelFont(axisFont);
        barPlot.getDomainAxis().setTickLabelFont(tickFont);
        barPlot.getRangeAxis().setLabelFont(axisFont);
        barPlot.getRangeAxis().setTickLabelFont(tickFont);

ChartPanel barPanel = new ChartPanel(barChart);
barPanel.setPreferredSize(fixedSize);
barPanel.setBackground(barChartBackgroundColor);
               
//        ChartPanel barPanel = new ChartPanel(barChart);
//        barPanel.setPreferredSize(fixedSize);
//        barPanel.setMaximumSize(fixedSize);
//        barPanel.setMinimumSize(fixedSize);
//        barPanel.setSize(fixedSize);

        chartContainer.setLayout(new FlowLayout(FlowLayout.CENTER, 40, 20));  // 40px horizontal gap, 20px vertical
        chartContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 10, 30, 10)); // top/bottom padding

        chartContainer.removeAll();
        chartContainer.add(barPanel);
        chartContainer.add(Box.createRigidArea(new Dimension(40, 0)));  // 40px horizontal spacing
        chartContainer.add(piePanel);
        chartContainer.revalidate();
        chartContainer.repaint();

        System.out.println("Donated: " + donated + ", Stored: " + stored);

    }

    private void loadSummaryMetrics() {
        int totalDonated = 0;
        int totalStored = 0;
        double energySavedPerItem = 0.5; // Example: 0.5 kWh saved per item

        for (NetWork net : foodShelterSystem.getNetworkList()) {
            for (BasicEnterprise be : net.getEnterpriseDirectory().getEnterprises()) {
                for (BasicOrganization org : be.getOrganizationDirectory().getOrganizationList()) {
                    for (WorkRequest wr : org.getWorkQueue().getWorkRequestList()) {

                        if (wr instanceof WorkRequestFoodItem && !(wr instanceof WorkRequestDelivery) && !(wr instanceof DeliveryTask)) {
                            WorkRequestFoodItem foodReq = (WorkRequestFoodItem) wr;
                            FoodItem item = foodReq.getFoodItem();
                            if (item != null && "stored".equalsIgnoreCase(item.getUsingStatus())) {
                                totalStored += item.getNumber();
                                System.out.println("Metrics - Adding to stored: " + item.getFoodName() + " - " + item.getNumber());
                            }
                        }

                        // Donated Food: taskStatus is "Delivered"
                        if (wr instanceof WorkRequestDelivery) {
                            WorkRequestDelivery deliveryReq = (WorkRequestDelivery) wr;
                            if (deliveryReq.getFoodItem() != null
                                    && "Delivered".equalsIgnoreCase(deliveryReq.getTaskStatus())) {
                                totalDonated += deliveryReq.getFoodItem().getNumber();
                                System.out.println("Metrics - Adding to donated (delivery): "
                                        + deliveryReq.getFoodItem().getFoodName() + " - "
                                        + deliveryReq.getFoodItem().getNumber());
                            }
                        } else if (wr instanceof DeliveryTask) {
                            DeliveryTask deliveryTask = (DeliveryTask) wr;
                            if ("Delivered".equalsIgnoreCase(deliveryTask.getStatus())) {
                                totalDonated += deliveryTask.getQuantity();
                                System.out.println("Metrics - Adding to donated (task): "
                                        + (deliveryTask.getFoodItem() != null
                                        ? deliveryTask.getFoodItem().getFoodName() : "Unknown")
                                        + " - " + deliveryTask.getQuantity());
                            }
                        }
                    }
                }
            }
        }
        
        for (NetWork net : foodShelterSystem.getNetworkList()) {
            if (net.getWarehouseList() != null) {
                for (WorkRequest wr : net.getWarehouseList().getWorkRequestList()) {
                    if (wr instanceof WorkRequestFoodItem && !(wr instanceof WorkRequestDelivery)) {
                        WorkRequestFoodItem foodReq = (WorkRequestFoodItem) wr;
                        FoodItem item = foodReq.getFoodItem();
                        if (item != null && "stored".equalsIgnoreCase(item.getUsingStatus())) {
                            totalStored += item.getNumber();
                            System.out.println("Metrics - Adding to stored from warehouse: "
                                    + item.getFoodName() + " - " + item.getNumber());
                        }
                    }
                }
            }
        }

        double totalEnergySaved = totalDonated * energySavedPerItem;

        lblTotalDonated.setText("🍽 Total Food Donated: " + totalDonated/2);

        lblEnergySaved.setText("💡 Estimated Energy Saved: " + totalEnergySaved/2 + " kWh");       
        lblTotalStored.setText("🥫 Total Food Stored: " + totalStored/2);

//        lblTotalDonated.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 15));
//        lblTotalDonated.setForeground(new Color(54, 33, 89));
//
//        lblEnergySaved.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 15));
//        lblEnergySaved.setForeground(new Color(54, 33, 89));
//        
//        lblTotalStored.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 15));
//        lblTotalStored.setForeground(new Color(54, 33, 89));

    }

    //////////////////beautify///////////////////
    public void beautify() {
        // 整体背景统一
        this.setBackground(new Color(245, 242, 250)); // 淡紫灰
        chartContainer.setBackground(new Color(245, 242, 250));

        // 标题字体
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        jLabel1.setForeground(new Color(54, 33, 89)); // 深紫色
        
        // 按钮样式
        BtnBack.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        BtnBack.setBackground(new java.awt.Color(103, 58, 183)); // 深紫色
        BtnBack.setForeground(java.awt.Color.WHITE);
        BtnBack.setFocusPainted(false);
        BtnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        
        btnExport.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        btnExport.setBackground(new java.awt.Color(33, 150, 243));
        btnExport.setForeground(java.awt.Color.WHITE);
        btnExport.setFocusPainted(false);
        btnExport.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));

        // 标签字体优化
        lblTotalDonated.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        lblTotalDonated.setForeground(new Color(60, 60, 60));
        lblEnergySaved.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        lblEnergySaved.setForeground(new Color(60, 60, 60));
        lblTotalStored.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        lblTotalStored.setForeground(new Color(60, 60, 60));

    }

    private void exportReportAsPDF() {

        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Save Report As PDF");
    fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

    int result = fileChooser.showSaveDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        File pdfFile = fileChooser.getSelectedFile();
        if (!pdfFile.getName().endsWith(".pdf")) {
            pdfFile = new File(pdfFile.getAbsolutePath() + ".pdf");
        }

        try {
            // Step 1: Create Document and PDF Writer
            Document document = new Document(PageSize.A4);
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(pdfFile));
            document.open();

            // Step 2: Add title
            com.itextpdf.text.Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, com.itextpdf.text.BaseColor.DARK_GRAY);
            Paragraph title = new Paragraph("📊 Food Donation Report", titleFont);
                    
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);    
            
            com.itextpdf.text.Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 14);
            document.add(new Paragraph(lblTotalDonated.getText(), bodyFont));
            document.add(new Paragraph(lblEnergySaved.getText(), bodyFont));
          document.add(new Paragraph(lblTotalStored.getText(), bodyFont));


            // Step 3: Add summary metrics
           
            document.add(Chunk.NEWLINE);

            // Step 4: Add charts as images
            for (java.awt.Component comp : chartContainer.getComponents()) {
                if (comp instanceof ChartPanel) {
                    JFreeChart chart = ((ChartPanel) comp).getChart();
                     BufferedImage image = chart.createBufferedImage(500, 300);
                    Image chartImg = Image.getInstance(writer, image, 1.0f);
                    chartImg.setAlignment(Image.ALIGN_CENTER);
                    chartImg.setSpacingBefore(10f);
                    chartImg.setSpacingAfter(20f);
                    document.add(chartImg);
                }
            }

            document.close();
            JOptionPane.showMessageDialog(this, "PDF saved to:\n" + pdfFile.getAbsolutePath());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Export failed:\n" + e.getMessage());
        }
    }
    }

    private void exportChartsAsImage() {

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Folder to Save Charts");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int result = fileChooser.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File dir = fileChooser.getSelectedFile();

            try {
                for (java.awt.Component comp : chartContainer.getComponents()) {
                    if (comp instanceof ChartPanel) {
                        ChartPanel chartPanel = (ChartPanel) comp;
                        String chartTitle = chartPanel.getChart().getTitle().getText().toLowerCase().replaceAll("\\s+", "_");
                        File outputFile = new File(dir, chartTitle + ".png");
                        ImageIO.write(chartPanel.getChart().createBufferedImage(600, 400), "png", outputFile);
                    }
                }
                JOptionPane.showMessageDialog(this, "Charts exported to:\n" + dir.getAbsolutePath());
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Export failed:\n" + e.getMessage());
            }
        }
    }

}

