/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ReportAnalystWorkArea;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import javax.swing.JPanel;
import model.Account.UserAccount;
import model.FoodItem.FoodItem;
import model.FoodShelterSystem.FoodShelterSystem;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestFoodItem;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import ui.AdminWorkArea.AdminStartPoint;
import ui.AdminWorkArea.viewNetWorkDetailPanel;

/**
 *
 * @author yuewu
 */
public class SummaryMetricsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SummaryMetricsPanel
     */
    FoodShelterSystem foodShelterSystem;
    JPanel workArea;
    UserAccount account;
    public SummaryMetricsPanel(JPanel workArea,FoodShelterSystem foodShelterSystem,UserAccount ua) {
        this.foodShelterSystem = foodShelterSystem;
        this.workArea = workArea;
        this.account = ua;
        initComponents();

        loadSummaryMetrics();

        showChart();
        beautify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalDonated = new javax.swing.JLabel();
        lblEnergySaved = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();

        chartContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SummaryMetrics");

        lblTotalDonated.setText("Total Food Donated: ");

        lblEnergySaved.setText("Estimated Energy Saved:");

        BtnBack.setText("<<  Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(chartContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnBack)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addComponent(lblEnergySaved)
                    .addComponent(lblTotalDonated))
                .addContainerGap(495, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(BtnBack))
                .addGap(20, 20, 20)
                .addComponent(lblTotalDonated)
                .addGap(18, 18, 18)
                .addComponent(lblEnergySaved)
                .addGap(18, 18, 18)
                .addComponent(chartContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        AdminStartPoint adminStartPoint = new AdminStartPoint(workArea, account, foodShelterSystem);
        workArea.add("AdminStartPoint",adminStartPoint);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "AdminStartPoint");
    }//GEN-LAST:event_BtnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JPanel chartContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnergySaved;
    private javax.swing.JLabel lblTotalDonated;
    // End of variables declaration//GEN-END:variables

    private void showChart() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        int donated = 0;
        int stored = 0;

        for (WorkRequest wr : foodShelterSystem.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof WorkRequestFoodItem) {
                FoodItem item = ((WorkRequestFoodItem) wr).getFoodItem();
                if (item.getUsingStatus().equalsIgnoreCase("Send")) {
                    donated += item.getNumber();
                } else {
                    stored += item.getNumber();
                }
            }
        }
        // pie chart
        dataset.setValue("Donated", donated);
        dataset.setValue("Stored", stored);

        JFreeChart pieChart = ChartFactory.createPieChart(
                "Food Usage Distribution",
                dataset,
                true,
                true,
                false);

        PiePlot plot = (PiePlot) pieChart.getPlot();
        plot.setSectionPaint("Donated", new Color(138, 201, 25)); // light blue
        plot.setSectionPaint("Stored", new Color(255, 175, 204)); // light orange
        plot.setBackgroundPaint(new Color(242, 242, 242));
        pieChart.setBackgroundPaint(new Color(242, 242, 242));

        plot.setOutlineVisible(false);
        plot.setShadowPaint(null);
        pieChart.removeLegend(); // optional

        Dimension fixedSize = new Dimension(280, 240);

        ChartPanel piePanel = new ChartPanel(pieChart);

        piePanel.setPreferredSize(fixedSize);
        piePanel.setMaximumSize(fixedSize);
        piePanel.setMinimumSize(fixedSize);
        piePanel.setSize(fixedSize);

        // bar chart

        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        barDataset.setValue(donated, "Food", "Donated");
        barDataset.setValue(stored, "Food", "Stored");

        JFreeChart barChart = ChartFactory.createBarChart(
                "Donation Summary",
                "Status",
                "Quantity",
                barDataset,
                PlotOrientation.VERTICAL,
                false, true, false);

        ChartPanel barPanel = new ChartPanel(barChart);
        barPanel.setPreferredSize(fixedSize);
        barPanel.setMaximumSize(fixedSize);
        barPanel.setMinimumSize(fixedSize);
        barPanel.setSize(fixedSize);

        chartContainer.removeAll();
        // chartContainer.setLayout(new GridBagLayout()); // center and stop stretch
        chartContainer.add(barPanel);
        chartContainer.add(piePanel);
        chartContainer.revalidate();
        chartContainer.repaint();
        barChart.setBackgroundPaint(new Color(245, 242, 250));
        barChart.getCategoryPlot().setBackgroundPaint(new Color(245, 242, 250));
        barChart.getCategoryPlot().setDomainGridlinePaint(new Color(200, 200, 230));
        barChart.getCategoryPlot().setRangeGridlinePaint(new Color(200, 200, 230));

        System.out.println("Donated: " + donated + ", Stored: " + stored);

    }

    private void loadSummaryMetrics() {

        System.out.println("Checking work requests...");
        for (WorkRequest wr : foodShelterSystem.getWorkQueue().getWorkRequestList()) {
            System.out.println(wr); // or wr.getClass().getSimpleName()
        }

        int totalDonated = 0;
        double energySavedPerItem = 0.5; // Example: 0.5 kWh saved per item

        for (WorkRequest wr : foodShelterSystem.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof WorkRequestFoodItem) {
                FoodItem item = ((WorkRequestFoodItem) wr).getFoodItem();
                if (item.getUsingStatus().equalsIgnoreCase("Send")) {
                    totalDonated += item.getNumber();
                }
            }
        }

        double totalEnergySaved = totalDonated * energySavedPerItem;

        lblTotalDonated.setText("Total Food Donated: " + totalDonated);
        lblEnergySaved.setText("Estimated Energy Saved: " + totalEnergySaved + " kWh");
    }

    //////////////////beautify///////////////////
    public void beautify() {
        // 整体背景统一
        this.setBackground(new Color(245, 242, 250)); // 淡紫灰
        chartContainer.setBackground(new Color(245, 242, 250));

        // 标题字体
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        jLabel1.setForeground(new Color(54, 33, 89)); // 深紫色

        // 标签字体优化
        lblTotalDonated.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        lblTotalDonated.setForeground(new Color(60, 60, 60));
        lblEnergySaved.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        lblEnergySaved.setForeground(new Color(60, 60, 60));

    }

}
