/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HomelessWorkArea;

import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.FoodEnterprise;
import model.Enterprise.RescueNetEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.FoodIncOrg;
import model.Organization.RequestCollectOrg;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestNeeds;

/**
 *
 * @author sylvia
 */
public class FoodRequestPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private UserAccount account;
    private RequestCollectOrg requestCollectOrg;
    private RescueNetEnterprise rescueNetEnterprise;
    private NetWork netWork;

    /**
     * Creates new form FoodRequestPanel
     */
    public FoodRequestPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        initComponents();
        this.workArea = workArea;
        this.account = account;
        this.requestCollectOrg = (RequestCollectOrg) organization;
        this.rescueNetEnterprise = (RescueNetEnterprise) enterprise;
        this.netWork = netWork;

        populateFoodOrgComboBox();
        beautify();
    }

    private void populateFoodOrgComboBox() {
        ComboBoxType.removeAllItems();

        for (BasicEnterprise enterprise : netWork.getEnterpriseDirectory().getEnterprises()) {
            if (enterprise instanceof FoodEnterprise) {
                FoodEnterprise foodEnt = (FoodEnterprise) enterprise;

                for (FoodIncOrg org : foodEnt.getFoodIncOrgs()) {
                    ComboBoxType.addItem(org.getName());
                }

            }

        }

        if (ComboBoxType.getItemCount() == 0) {
            ComboBoxType.addItem("No Food Organizations Available");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        spinnerQuantity = new javax.swing.JSpinner();
        valueLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnViewRequests = new javax.swing.JButton();
        ComboBoxType = new javax.swing.JComboBox<>();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("My Request Table");

        valueLabel.setText("Quantity:");

        valueLabel1.setText("Vendor:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnViewRequests.setText("View Requests");
        btnViewRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestsActionPerformed(evt);
            }
        });

        ComboBoxType.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(156, 156, 156)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(valueLabel1)
                                                                        .addComponent(valueLabel))
                                                                .addGap(25, 25, 25)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(spinnerQuantity,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(ComboBoxType,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel4)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(125, 125, 125)
                                                .addComponent(btnSubmit)
                                                .addGap(87, 87, 87)
                                                .addComponent(btnViewRequests)))
                                .addContainerGap(186, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(valueLabel1)
                                        .addComponent(ComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(valueLabel))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSubmit)
                                        .addComponent(btnViewRequests))
                                .addContainerGap(86, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        String foodOrgName = ComboBoxType.getSelectedItem().toString();
        int quantity = (Integer) spinnerQuantity.getValue();

        if (foodOrgName == null || foodOrgName.isEmpty() || quantity <= 0) {
            JOptionPane.showMessageDialog(null, "Please select a food organization and enter a valid quantity.");
            return;
        }

        WorkRequest request = new WorkRequestNeeds();
        request.setFoodOrgName(foodOrgName);
        request.setQuantity(quantity);
        request.setSender(requestCollectOrg);
        request.setStatus("Pending");
        request.setRequestDate(new Date());

        request.setMessage(foodOrgName + " - " + quantity + " items");
        for (BasicEnterprise enterprise : netWork.getEnterpriseDirectory().getEnterprises()) {
            if (enterprise instanceof RescueNetEnterprise) {
                RescueNetEnterprise rescueEnt = (RescueNetEnterprise) enterprise;
                request.setReceiver(rescueEnt.getRequestEntertainOrg());
                break;
            }
        }
        requestCollectOrg.getWorkQueue().getWorkRequestList().add(request);

        JOptionPane.showMessageDialog(null, "Food request submitted successfully!");

        spinnerQuantity.setValue(0);
    }// GEN-LAST:event_btnSubmitActionPerformed

    private void ComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ComboBoxTypeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ComboBoxTypeActionPerformed

    private void btnViewRequestsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnViewRequestsActionPerformed
        // TODO add your handling code here:
        HomelessWorkPanel panel = new HomelessWorkPanel(workArea, account, requestCollectOrg, rescueNetEnterprise,
                netWork);

        workArea.add("HomelessWorkPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "HomelessWorkPanel");
        workArea.revalidate();
        workArea.repaint();
    }// GEN-LAST:event_btnViewRequestsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxType;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewRequests;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;

    // End of variables declaration//GEN-END:variables
    private void beautify() {
        // 背景
        this.setBackground(new java.awt.Color(245, 242, 250)); // 淡紫灰

        // 标题样式
        jLabel4.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        jLabel4.setForeground(new java.awt.Color(54, 33, 89)); // 深紫标题

        // 标签字体
        java.awt.Font labelFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
        java.awt.Color labelColor = new java.awt.Color(80, 80, 80);
        valueLabel.setFont(labelFont);
        valueLabel.setForeground(labelColor);
        valueLabel1.setFont(labelFont);
        valueLabel1.setForeground(labelColor);

        // Spinner 样式
        spinnerQuantity.setFont(labelFont);
        spinnerQuantity.setForeground(new java.awt.Color(40, 40, 40));
        spinnerQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));

        // ComboBox 美化
        ComboBoxType.setFont(labelFont);
        ComboBoxType.setForeground(new java.awt.Color(33, 33, 33));
        ComboBoxType.setBackground(java.awt.Color.WHITE);
        ComboBoxType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));

        ComboBoxType.setRenderer(new javax.swing.plaf.basic.BasicComboBoxRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index,
                    boolean isSelected, boolean cellHasFocus) {
                java.awt.Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                c.setFont(labelFont);
                if (isSelected) {
                    c.setBackground(new java.awt.Color(230, 240, 255));
                    c.setForeground(new java.awt.Color(0, 123, 255));
                } else {
                    c.setBackground(java.awt.Color.WHITE);
                    c.setForeground(new java.awt.Color(33, 33, 33));
                }
                return c;
            }
        });

        // 按钮统一美化
        javax.swing.JButton[] buttons = { btnSubmit, btnViewRequests };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(labelFont);
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }
    }
}
