/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HomelessWorkArea;

import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.FoodEnterprise;
import model.Enterprise.RescueNetEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.FoodIncOrg;
import model.Organization.RequestCollectOrg;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestNeeds;

/**
 *
 * @author sylvia
 */
public class FoodRequestPanel extends javax.swing.JPanel {
    
    private JPanel workArea;
    private UserAccount account;
    private RequestCollectOrg requestCollectOrg;
    private RescueNetEnterprise rescueNetEnterprise;
    private NetWork netWork;

    /**
     * Creates new form FoodRequestPanel
     */
    public FoodRequestPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
                        BasicEnterprise enterprise, NetWork netWork) {
        initComponents();
        this.workArea = workArea;
        this.account = account;
        this.requestCollectOrg = (RequestCollectOrg) organization;
        this.rescueNetEnterprise = (RescueNetEnterprise) enterprise;
        this.netWork = netWork;

        populateFoodOrgComboBox();
    }
    
    private void populateFoodOrgComboBox() {
    ComboBoxType.removeAllItems();
    
    for (BasicEnterprise enterprise : netWork.getEnterpriseDirectory().getEnterprises()) {
        if (enterprise instanceof FoodEnterprise) {
            FoodEnterprise foodEnt = (FoodEnterprise) enterprise;
            
            for (FoodIncOrg org : foodEnt.getFoodIncOrgs()) {
                ComboBoxType.addItem(org.getName());
            }
            
           
            }
        
    }
    
    if (ComboBoxType.getItemCount() == 0) {
        ComboBoxType.addItem("No Food Organizations Available");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        spinnerQuantity = new javax.swing.JSpinner();
        valueLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnViewRequests = new javax.swing.JButton();
        ComboBoxType = new javax.swing.JComboBox<>();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("My Request Table");

        valueLabel.setText("Quantity:");

        valueLabel1.setText("Vendor:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnViewRequests.setText("View Requests");
        btnViewRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestsActionPerformed(evt);
            }
        });

        ComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnSubmit)
                        .addGap(91, 91, 91)
                        .addComponent(btnViewRequests))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(valueLabel)
                                    .addComponent(valueLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel1)
                    .addComponent(ComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel)
                    .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnViewRequests))
                .addContainerGap(274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

    String foodOrgName = ComboBoxType.getSelectedItem().toString();
    int quantity = (Integer) spinnerQuantity.getValue();


    if (foodOrgName == null || foodOrgName.isEmpty() || quantity <= 0) {
        JOptionPane.showMessageDialog(null, "Please select a food organization and enter a valid quantity.");
        return;
    }

    WorkRequest request = new WorkRequestNeeds();
    request.setFoodOrgName(foodOrgName);
    request.setQuantity(quantity);
    request.setSender(requestCollectOrg);
    request.setStatus("Pending");
    request.setRequestDate(new Date());

    request.setMessage(foodOrgName + " - " + quantity + " items");
    for (BasicEnterprise enterprise : netWork.getEnterpriseDirectory().getEnterprises()) {
        if (enterprise instanceof RescueNetEnterprise) {
            RescueNetEnterprise rescueEnt = (RescueNetEnterprise) enterprise;
            request.setReceiver(rescueEnt.getRequestEntertainOrg());
            break;
        }
    }
    requestCollectOrg.getWorkQueue().getWorkRequestList().add(request);

    JOptionPane.showMessageDialog(null, "Food request submitted successfully!");
    
    spinnerQuantity.setValue(0);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void ComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTypeActionPerformed

    private void btnViewRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestsActionPerformed
        // TODO add your handling code here:
    HomelessWorkPanel panel = new HomelessWorkPanel(workArea, account, requestCollectOrg, rescueNetEnterprise, netWork);
    
    workArea.add("HomelessWorkPanel", panel);
    
    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.show(workArea, "HomelessWorkPanel");
    }//GEN-LAST:event_btnViewRequestsActionPerformed


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxType;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewRequests;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables
}
