/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HomelessWorkArea;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.RescueNetEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.RequestCollectOrg;
import model.WorkQueue.WorkRequest;

/**
 *
 * @author sylvia
 */
public class HomelessWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomelessWorkPanel
     */
    NetWork netWork;
    JPanel workArea;
    RequestCollectOrg requestCollectOrg;
    RescueNetEnterprise rescueNetEnterprise;
    private UserAccount account;

    public HomelessWorkPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        this.netWork = netWork;
        this.workArea = workArea;
        this.requestCollectOrg = (RequestCollectOrg) organization;
        this.rescueNetEnterprise = (RescueNetEnterprise) enterprise;
        this.account = account;
        initComponents();

        populateTable();
        beautify();

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
        model.setRowCount(0);

        for (WorkRequest request : requestCollectOrg.getWorkQueue().getWorkRequestList()) {

            if (request.getSender() != null && request.getSender().equals(account.getOrganization())) {
                Object[] row = new Object[3];
                row[0] = request.getFoodOrgName();
                row[1] = request.getStatus();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnWithdraw = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("My Request Table");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        btnWithdraw.setText("Withdraw Request");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnWithdraw)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(btnBack)
                            .addGap(90, 90, 90)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnWithdraw)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FoodRequestPanel panel = new FoodRequestPanel(workArea, account, requestCollectOrg, rescueNetEnterprise,
                netWork);
        workArea.removeAll();
        workArea.add("FoodRequestPanel", panel);
        workArea.revalidate();
        workArea.repaint();

    }// GEN-LAST:event_btnBackActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request to withdraw.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
        String selectedFoodOrgName = model.getValueAt(selectedRow, 0).toString();
        String selectedStatus = model.getValueAt(selectedRow, 1).toString();

        // 注意注意～只允许撤回 Pending 状态的请求
        if (!selectedStatus.equalsIgnoreCase("Pending")) {
            JOptionPane.showMessageDialog(null, "Only pending requests can be withdrawn.");
            return;
        }

        // 在 WorkQueue中移除的！
        WorkRequest toRemove = null;
        for (WorkRequest req : requestCollectOrg.getWorkQueue().getWorkRequestList()) {
            if (req.getSender().equals(account.getOrganization()) &&
                    req.getFoodOrgName().equals(selectedFoodOrgName) &&
                    req.getStatus().equalsIgnoreCase("Pending")) {
                toRemove = req;
                break;
            }
        }

        if (toRemove != null) {
            requestCollectOrg.getWorkQueue().removeWorkRequest(toRemove);
            JOptionPane.showMessageDialog(null, "Request withdrawn successfully.");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Unable to find the request to withdraw.");
        }
    }// GEN-LAST:event_btnWithdrawActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void beautify() {
        // 设置背景色
        this.setBackground(new java.awt.Color(245, 242, 250)); // 淡紫灰背景

        // 标题样式
        jLabel4.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        jLabel4.setForeground(new java.awt.Color(54, 33, 89)); // 深紫

        // 按钮样式
        javax.swing.JButton[] buttons = { btnBack, btnWithdraw };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫按钮
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }

        // 表格样式
        jTable1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        jTable1.setRowHeight(28);
        jTable1.setGridColor(new java.awt.Color(200, 190, 230)); // 紫灰边框
        jTable1.setForeground(new java.awt.Color(33, 33, 33));
        jTable1.setSelectionBackground(new java.awt.Color(190, 170, 240));
        jTable1.setSelectionForeground(java.awt.Color.WHITE);

        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        jTable1.getTableHeader().setBackground(new java.awt.Color(230, 225, 250));
        jTable1.getTableHeader().setForeground(new java.awt.Color(54, 33, 89));

        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
    }

}
