/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DriverWorkArea;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.VolunteerEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.DriverOrg;
import model.Role.Deliver;
import model.WorkQueue.*;

/**
 *
 * @author sylvia
 */
public class DriverWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverWorkPanel
     */
    JPanel workArea;
    VolunteerEnterprise volunteerEnterprise;
    DriverOrg driverOrg;
    NetWork netWork;
    UserAccount driver;
    public DriverWorkPanel(JPanel workArea, BasicEnterprise enterprise,BasicOrganization organization,NetWork netWork,UserAccount userAccount) {
        this.workArea = workArea;
        this.volunteerEnterprise =(VolunteerEnterprise)enterprise;
        this.driverOrg = (DriverOrg)organization;
        this.netWork = netWork;
        this.driver = userAccount;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaskTable = new javax.swing.JTable();
        DeliveredBtn = new javax.swing.JButton();
        getItemBtn = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Delivery Task List");

        TaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Task ID", "Food Name", "Quantity", "From", "To", "Stauts"
            }
        ));
        jScrollPane1.setViewportView(TaskTable);

        DeliveredBtn.setText("Confirm Delivery");
        DeliveredBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveredBtnActionPerformed(evt);
            }
        });

        getItemBtn.setText("Confirm getItem");
        getItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getItemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(getItemBtn)
                        .addGap(98, 98, 98)
                        .addComponent(DeliveredBtn)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeliveredBtn)
                    .addComponent(getItemBtn))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeliveredBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveredBtnActionPerformed
        // TODO add your handling code here:
        int rowNumber = TaskTable.getSelectedRow();
        if(rowNumber<0){
            JOptionPane.showMessageDialog(this, "Please select a row first");
            return;
        }
        WorkRequestDelivery wrd = (WorkRequestDelivery) TaskTable.getValueAt(5, rowNumber);
        
        if (wrd != null) {
            wrd.setStatus("delivered");
            populateTable();
            JOptionPane.showMessageDialog(this, "Delivery confirmed successfully.");
        } else{
            JOptionPane.showMessageDialog(this, "Error: Could not update delivery status.");

        }
    }//GEN-LAST:event_DeliveredBtnActionPerformed

    private void getItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getItemBtnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int rowNumber = TaskTable.getSelectedRow();
        if(rowNumber<0){
            JOptionPane.showMessageDialog(this, "Please select a row first");
            return;
        }
        WorkRequestDelivery wrd = (WorkRequestDelivery) TaskTable.getValueAt(5, rowNumber);
        wrd.setStatus("picked up");

        populateTable();
    }//GEN-LAST:event_getItemBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeliveredBtn;
    private javax.swing.JTable TaskTable;
    private javax.swing.JButton getItemBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /////// my funcation///////////////
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) TaskTable.getModel();
        model.setRowCount(0);
        // 从userAccount的workQueue中获得
        Deliver deliver = (Deliver) this.driver.getRole();
        WorkQueue workQueue = deliver.getWorkQueue();
        int count =0;
        for (WorkRequest wd : workQueue.getWorkRequestList()) {
            WorkRequestDelivery wrd = (WorkRequestDelivery) wd;
            count++;
            Object row[] = new Object[6];
            row[0] = count;
            row[1] = wrd.getFoodItem().getFoodName();
            row[2] = wrd.getFoodItem().getNumber();
            row[3] = wrd.getSender().getAddress();
            row[4] = wrd.getReceiver().getAddress();
            row[5] = wrd;
            // r[4]存储的是原来的workrequest
            model.addRow(row);
        }
    }

}
