/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account.UserAccount;
import model.FoodShelterSystem.FoodShelterSystem;
import model.DB4OUtil.DB4OUtil;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.FoodEnterprise;
import model.Organization.BasicOrganization;
import model.NetWork.NetWork;
import model.Role.SysAdmin;

/**
 *
 * @author 59386
 */
public class main extends javax.swing.JFrame {

    private FoodShelterSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        setResizable(false);
        setSize(1200, 900);
        jSplitPane1.setDividerLocation(0.2);
        WelcomeJPanel welcomeJPanel = new WelcomeJPanel();
        container.add("WelComeJPanel", welcomeJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.show(container, "WelComeJPanel");
        populateCombox();

        // make sure system are stored correctely
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                dB4OUtil.storeSystem(system); // 自动保存系统状态
                System.out.println("系统数据已保存（窗口关闭）");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("User Name");

        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });

        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("NetWork Select");

        jLabel4.setText("Password");

        combox.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(passwordField,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                94, Short.MAX_VALUE)
                                                                        .addComponent(loginJButton,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(logoutJButton,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(userNameJTextField))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(24, 24, 24)
                                                                .addComponent(jLabel4))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addComponent(jLabel1))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(combox, javax.swing.GroupLayout.Alignment.TRAILING, 0,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
                new java.awt.Component[] { passwordField, userNameJTextField });

        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loginJButton)
                                .addGap(18, 18, 18)
                                .addComponent(logoutJButton)
                                .addContainerGap(321, Short.MAX_VALUE)));

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_userNameJTextFieldActionPerformed

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String userName = userNameJTextField.getText();
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        Object selectedItem = combox.getSelectedItem();
        if (selectedItem == null) {
            JOptionPane.showMessageDialog(null, "Please select System or a specific Network first.");
            return;
        }

        UserAccount userAccount = null;
        NetWork inNetwork = null;
        BasicEnterprise inEnterprise = null;
        BasicOrganization inOrganization = null;

        if (selectedItem instanceof FoodShelterSystem) {
            // 如果选中的是 system，则遍历所有 network
            for (NetWork network : system.getNetworkList()) {
                userAccount = network.getUserAccountDirctory().authenticateUser(userName, password);
                if (userAccount != null) {
                    if (!(userAccount.getRole() instanceof SysAdmin)) {
                        JOptionPane.showMessageDialog(null, "You are not the system admin.");
                        return;
                    }
                    inNetwork = network;
                    break;
                }
            }
        } else if (selectedItem instanceof NetWork) {
            // 只在选中的 Network 中查找
            NetWork selectedNetwork = (NetWork) selectedItem;
            userAccount = selectedNetwork.getUserAccountDirctory().authenticateUser(userName, password);
            if (userAccount != null) {
                inNetwork = selectedNetwork;
            }
        }

        // 后续逻辑：查找所属的 enterprise 和 organization
        if (userAccount != null && inNetwork != null) {
            if (userAccount.getEnterprise() != null) {
                inEnterprise = userAccount.getEnterprise();
            }

        if (inEnterprise == null || userAccount.getOrganization() != null) {
            inOrganization = userAccount.getOrganization();

            for (BasicEnterprise enterprise : inNetwork.getEnterpriseDirectory().getEnterprises()) {
                if (enterprise.getOrganizationDirectory().getOrganizationList().contains(inOrganization)) {
                    inEnterprise = enterprise;
                    break;
                }

                if (enterprise instanceof FoodEnterprise) {
                    FoodEnterprise foodEnt = (FoodEnterprise) enterprise;
                    if (foodEnt.getFoodIncOrgs().contains(inOrganization)) {
                        inEnterprise = enterprise;
                        break;
                    }
                }
            }
        }

        if (inEnterprise == null) {
            for (BasicEnterprise enterprise : inNetwork.getEnterpriseDirectory().getEnterprises()) {
                if (enterprise.getUserAccountDirectory().getUserAccountList().contains(userAccount)) {
                    inEnterprise = enterprise;
                    break;
                }

                for (BasicOrganization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization.getUserAccountDirectory().getUserAccountList().contains(userAccount)) {
                        inEnterprise = enterprise;
                        inOrganization = organization;
                        break;
                    }
                }

                    if (inEnterprise != null) {
                        break;
                    }
                }
            }
        }

        if (userAccount == null || inNetwork == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }

        // 登录成功后跳转面板
        container.removeAll();
        JPanel workArea = userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, inNetwork, system);
        container.add("workArea", workArea);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.show(container, "workArea");

        loginJButton.setEnabled(false);
        logoutJButton.setEnabled(true);
        userNameJTextField.setEnabled(false);
        passwordField.setEnabled(false);
        combox.setEnabled(false);

    }

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutJButtonActionPerformed
        logoutJButton.setEnabled(false);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        loginJButton.setEnabled(true);

        userNameJTextField.setText("");
        passwordField.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        combox.setEnabled(true);
        dB4OUtil.storeSystem(system);
    }// GEN-LAST:event_logoutJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> combox;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables

    //////////////////////////////////////////////////
    /// populate Combox
    public void populateCombox() {
        combox.removeAllItems();
        combox.addItem("Select Network or System");
        combox.addItem(system);
        System.out.println(system.getNetworkList().size());
        for (NetWork netWork1 : system.getNetworkList()) {
            System.out.println(netWork1.getName());
            combox.addItem(netWork1);
        }
    }

}
