/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FoodProviderWorkArea;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.FoodEnterprise;
import model.FoodItem.FoodItem;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.FoodIncOrg;
import model.WorkQueue.WorkRequestFoodItem;

/**
 *
 * @author sylvia
 */
public class DonationFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonationFormPanel
     */
    JPanel workArea;
    NetWork netWork;
    FoodIncOrg foodIncOrg;
    FoodEnterprise foodEnterprise;
    UserAccount account;
    String ImgPath;

    public DonationFormPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.netWork = netWork;
        ImgPath="";
        initComponents();
        // add img
        ImageIcon icon = new ImageIcon(getClass().getResource("/Donate.png"));
        Image scaledImg = icon.getImage().getScaledInstance(500, 300, Image.SCALE_SMOOTH);
        imgLable.setIcon(new ImageIcon(scaledImg));

        this.account = account;

        if (account != null) {
            lblWelcome.setText("Welcome, " + account.getUsername() + " !");
        } else {
            lblWelcome.setText("Welcome, Guest!");
        }

        if (enterprise != null) {
            lblEnterprise.setText(enterprise.getName());
            if (enterprise instanceof FoodEnterprise) {
                this.foodEnterprise = (FoodEnterprise) enterprise;
            }
        } else {
            lblEnterprise.setText("No Enterprise");
        }

        if (organization != null && organization instanceof FoodIncOrg) {
            this.foodIncOrg = (FoodIncOrg) organization;
        }
        
        expiraDateSpinner.setModel(new javax.swing.SpinnerDateModel());
        expiraDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(expiraDateSpinner, "MM/dd/yyyy"));
        expiraDateSpinner.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));


        
        
        beautify();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        txtFoodName = new javax.swing.JTextField();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        spinnerQuantity = new javax.swing.JSpinner();
        valueLabel1 = new javax.swing.JLabel();
        btnResetForm = new javax.swing.JButton();
        requestTestJButton1 = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        imgLable = new javax.swing.JLabel();
        expiraDateSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        FoodIncon = new javax.swing.JLabel();
        btnImg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDesc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        requestTestJButton.setText("Submit Donation");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        valueLabel.setText("Quantity:");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Donation Form");

        valueLabel1.setText("Food Name:");

        btnResetForm.setText("Reset");
        btnResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormActionPerformed(evt);
            }
        });

        requestTestJButton1.setText("View My Donation");
        requestTestJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton1ActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblWelcome.setText("<Value>");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Enterprise: ");

        lblEnterprise.setText("<value>");

        jLabel1.setText("Expiration Date:");

        btnImg.setText("select img");
        btnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgActionPerformed(evt);
            }
        });

        TxtDesc.setColumns(20);
        TxtDesc.setRows(5);
        jScrollPane1.setViewportView(TxtDesc);

        jLabel3.setText("Img");

        jLabel4.setText("Food desc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEnterprise)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(valueLabel)
                                            .addComponent(valueLabel1)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFoodName)
                                            .addComponent(spinnerQuantity)
                                            .addComponent(expiraDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnImg)))
                                .addGap(220, 220, 220))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(requestTestJButton)
                        .addGap(29, 29, 29)
                        .addComponent(btnResetForm)
                        .addGap(27, 27, 27)
                        .addComponent(requestTestJButton1)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FoodIncon, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgLable, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(jLabel2)
                    .addComponent(lblEnterprise))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgLable, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valueLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valueLabel)
                                    .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(expiraDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnImg)
                                    .addComponent(jLabel3)))
                            .addComponent(FoodIncon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(requestTestJButton)
                            .addComponent(btnResetForm)
                            .addComponent(requestTestJButton1))
                        .addGap(115, 115, 115))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("upload homeless' incon（Img only） ");
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg", "gif");
        fileChooser.addChoosableFileFilter(filter);
        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                // 1. 保存图片到本地目录
                String targetDirPath = "uploadedImages";
                File dir = new File(targetDirPath);
                if (!dir.exists())
                    dir.mkdir();

                File destinationFile = new File(dir, selectedFile.getName());
                Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

                // 2. 显示图片
                ImageIcon imageIcon = new ImageIcon(destinationFile.getAbsolutePath());
                Image image = imageIcon.getImage().getScaledInstance(350, 200, Image.SCALE_SMOOTH);
                FoodIncon.setIcon(new ImageIcon(image));
                this.ImgPath = destinationFile.getAbsolutePath();

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error uploading image: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnImgActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_requestTestJButtonActionPerformed

        String foodName = txtFoodName.getText().trim();
        int quantity = (int) spinnerQuantity.getValue();

        // Validate food name
        if (foodName.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a food name.",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            txtFoodName.requestFocus();
            return;
        }

        // Validate quantity
        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a quantity greater than zero.",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            spinnerQuantity.requestFocus();
            return;
        }
        // First find the enterprise if it's null
        if (foodEnterprise == null && account != null) {
            // 直接从用户账户获取企业
            if (account.getEnterprise() != null && account.getEnterprise() instanceof FoodEnterprise) {
                foodEnterprise = (FoodEnterprise) account.getEnterprise();
                System.out.println("直接从用户账户获取企业: " + foodEnterprise.getName());
            } else {
                // 通过组织查找企业
                BasicOrganization org = account.getOrganization();
                if (org != null && org instanceof FoodIncOrg) {
                    // 如果组织是FoodIncOrg，找其所属的企业
                    foodIncOrg = (FoodIncOrg) org;

                    // 通过网络查找该组织所属的企业
                    if (netWork != null) {
                        for (BasicEnterprise ent : netWork.getEnterpriseDirectory().getEnterprises()) {
                            if (ent instanceof FoodEnterprise) {
                                FoodEnterprise foodEnt = (FoodEnterprise) ent;
                                if (foodEnt.getFoodIncOrgs().contains(foodIncOrg)) {
                                    foodEnterprise = foodEnt;
                                    System.out.println("通过组织在网络中找到企业: " + foodEnterprise.getName());
                                    break;
                                }
                            }
                        }
                    }
                }
            }
        }
        // Now find the FoodIncOrg if it's null
        if (foodIncOrg == null && foodEnterprise != null) {
            // First try the organization directory
            for (BasicOrganization org : foodEnterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof FoodIncOrg) {
                    foodIncOrg = (FoodIncOrg) org;
                    System.out.println("Found FoodIncOrg from org directory: " + foodIncOrg.getName());
                    break;
                }
            }

            // If still null, try the custom list
            if (foodIncOrg == null && !foodEnterprise.getFoodIncOrgs().isEmpty()) {
                foodIncOrg = foodEnterprise.getFoodIncOrgs().get(0);
                System.out.println("Found FoodIncOrg from custom list: " + foodIncOrg.getName());
            }
        }

        // Check again if both are still null
        if (foodEnterprise == null) {
            JOptionPane.showMessageDialog(this,
                    "Error: Food Enterprise is not properly initialized. Please log in again.");
            return;
        }

        if (foodIncOrg == null) {
            JOptionPane.showMessageDialog(this, "Error: Food Organization is not properly initialized.");
            return;
        }

        // Rest of your method...
        FoodItem fooditem = new FoodItem();
        fooditem.setFoodName(txtFoodName.getText().trim());
        fooditem.setNumber((int) spinnerQuantity.getValue());

        java.util.Date expiryDate = (java.util.Date) expiraDateSpinner.getValue();
        fooditem.setExpiredDate(new java.text.SimpleDateFormat("MM/dd/yyyy").format(expiryDate));

        fooditem.setFoodIncOrg(foodIncOrg);
        String desc = TxtDesc.getText();
        fooditem.setDecs(desc);
        if(this.ImgPath!=null && !this.ImgPath.equals("")){
            fooditem.setInconPath(ImgPath);
        }

        FoodIncOrg org = null;

        for (BasicOrganization candidate : foodEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (candidate instanceof FoodIncOrg) {
                org = (FoodIncOrg) candidate;
                break;
            }
        }

        if (org != null) {
            // Add null check for account
            if (account == null) {
                JOptionPane.showMessageDialog(this, "Error: User account is not initialized.");
                return;
            }

            WorkRequestFoodItem request = new WorkRequestFoodItem();
            request.setFoodItem(fooditem);
            request.setSender(foodIncOrg);
            request.setStatus("Pending");
            request.setRequestDate(new java.util.Date());

            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);

            // 要在network中展示
            netWork.getCheckList().getWorkRequestList().add(request);

            JOptionPane.showMessageDialog(this, "Donation submitted successfully!");
            txtFoodName.setText("");
            spinnerQuantity.setValue(0);
            expiraDateSpinner.setValue(new java.util.Date()); // reset to today
            TxtDesc.setText("");
            FoodIncon.setIcon(null);

        } else {
            JOptionPane.showMessageDialog(this, "Error: Could not find appropriate organization for donation.");
        }

    }// GEN-LAST:event_requestTestJButtonActionPerformed

    private void btnResetFormActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetFormActionPerformed
        // TODO add your handling code here:

        txtFoodName.setText("");
        spinnerQuantity.setValue(0);
        expiraDateSpinner.setValue(new java.util.Date()); // reset to today

    }// GEN-LAST:event_btnResetFormActionPerformed

    private void requestTestJButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_requestTestJButton1ActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) workArea.getLayout();
        workArea.add("MyDonationTablePanel",
                new MyDonationTablePanel(workArea, account, foodIncOrg, foodEnterprise, netWork));
        layout.show(workArea, "MyDonationTablePanel");
        workArea.revalidate();
        workArea.repaint();

    }// GEN-LAST:event_requestTestJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FoodIncon;
    private javax.swing.JTextArea TxtDesc;
    private javax.swing.JButton btnImg;
    private javax.swing.JButton btnResetForm;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JSpinner expiraDateSpinner;
    private javax.swing.JLabel imgLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton requestTestJButton1;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JTextField txtFoodName;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables
    private void beautify() {
        // 背景色统一
        this.setBackground(new java.awt.Color(245, 242, 250));

        // 主标题样式
        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        enterpriseLabel.setForeground(new java.awt.Color(54, 33, 89));

        // 欢迎文字
        lblWelcome.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        lblWelcome.setForeground(new java.awt.Color(60, 60, 60));

        // Enterprise 标签
        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        jLabel2.setForeground(new java.awt.Color(60, 60, 60));
        lblEnterprise.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        lblEnterprise.setForeground(new java.awt.Color(60, 60, 60));

        // 表单标签样式
        java.awt.Font labelFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
        java.awt.Color labelColor = new java.awt.Color(80, 80, 80);
        valueLabel.setFont(labelFont);
        valueLabel.setForeground(labelColor);
        valueLabel1.setFont(labelFont);
        valueLabel1.setForeground(labelColor);

        jLabel1.setFont(labelFont);
        jLabel1.setForeground(labelColor);
        jLabel1.setFont(labelFont);
        jLabel1.setForeground(labelColor);

        // 输入框样式
        txtFoodName.setFont(labelFont);
        txtFoodName.setBackground(java.awt.Color.WHITE);
        txtFoodName.setForeground(new java.awt.Color(40, 40, 40));
        txtFoodName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));


        spinnerQuantity.setFont(labelFont);
        spinnerQuantity.setForeground(new java.awt.Color(40, 40, 40));
        spinnerQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));

        // 按钮统一样式
        javax.swing.JButton[] buttons = { requestTestJButton, btnResetForm, requestTestJButton1 };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫按钮
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }
    }

}
