/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FoodProviderWorkArea;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.FoodEnterprise;
import model.FoodItem.FoodItem;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.FoodIncOrg;
import model.WorkQueue.WorkQueue;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestFoodItem;

/**
 *
 * @author sylvia
 */
public class MyDonationTablePanel extends javax.swing.JPanel {

        /**
         * Creates new form MyDonationTablePanel
         */

        JPanel workArea;
        NetWork netWork;
        FoodIncOrg foodIncOrg;
        FoodEnterprise foodEnterprise;
        UserAccount account;

        public MyDonationTablePanel(JPanel workArea, UserAccount account, BasicOrganization organization,
                        BasicEnterprise enterprise, NetWork netWork) {
                this.workArea = workArea;
                this.netWork = netWork;
                this.foodEnterprise = (FoodEnterprise) enterprise;
                this.foodIncOrg = (FoodIncOrg) organization;
                this.account = account;

                initComponents();
                // setImg
                ImageIcon icon = new ImageIcon(getClass().getResource("/MyDonation.png"));
                Image scaledImg = icon.getImage().getScaledInstance(480, 240, Image.SCALE_SMOOTH);
                imgLabel.setIcon(new ImageIcon(scaledImg));

                if (enterprise != null) {
                        lblEnterprise.setText(enterprise.getName());
                }

                populateTable();
                beautify();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonations = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        FoodImg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtDesc = new javax.swing.JTextArea();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("My Donation");

        tblDonations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Food ID", "Food Name", "Quantity", "Expiry Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDonations);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Enterprise: ");

        lblEnterprise.setText("<value>");

        btnCheck.setText("check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        TxtDesc.setColumns(20);
        TxtDesc.setRows(5);
        jScrollPane2.setViewportView(TxtDesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(101, 101, 101)
                        .addComponent(enterpriseLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnterprise))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCheck)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(FoodImg, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblEnterprise))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(FoodImg, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCheck)
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDonations.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row first.");
            return;
        }
        WorkRequestFoodItem wrd = (WorkRequestFoodItem) tblDonations.getValueAt(selectedRow, 0);
        if(wrd.getFoodItem().getDecs()!=null){
            TxtDesc.setText(wrd.getFoodItem().getDecs());
        }
        if(wrd.getFoodItem().getInconPath()!=null){
            ImageIcon icon = new ImageIcon(wrd.getFoodItem().getInconPath());
            Image scaledImg = icon.getImage().getScaledInstance(350, 240, Image.SCALE_SMOOTH);
            FoodImg.setIcon(new ImageIcon(scaledImg));
        }
        
    }//GEN-LAST:event_btnCheckActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:

                workArea.remove(this);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.show(workArea, "DonationFormPanel");
                workArea.revalidate();
                workArea.repaint();
        }// GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FoodImg;
    private javax.swing.JTextArea TxtDesc;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JTable tblDonations;
    // End of variables declaration//GEN-END:variables

        private void populateTable() {

                DefaultTableModel model = (DefaultTableModel) tblDonations.getModel();
                TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
                tblDonations.setRowSorter(sorter);
                model.setRowCount(0);
                // 从userAccount的workQueue中获得

                WorkQueue workQueue = account.getWorkQueue();

                for (WorkRequest request : workQueue.getWorkRequestList()) {

                        if (request instanceof WorkRequestFoodItem) {
                                WorkRequestFoodItem wrd = (WorkRequestFoodItem) request;
                                FoodItem foodItem = wrd.getFoodItem();

                                Object row[] = new Object[5];
                                row[0] = wrd;
                                row[1] = foodItem.getFoodName();
                                row[2] = foodItem.getNumber();
                                row[3] = foodItem.getExpiredDate();
                                row[4] = foodItem.getFoodStatus();
                                model.addRow(row);
                        }
                }
        }

        private void beautify() {
                // 整体背景
                this.setBackground(new java.awt.Color(245, 242, 250));

                // 标题样式
                enterpriseLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
                enterpriseLabel.setForeground(new java.awt.Color(54, 33, 89));

                // 企业标签
                jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
                jLabel2.setForeground(new java.awt.Color(60, 60, 60));
                lblEnterprise.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
                lblEnterprise.setForeground(new java.awt.Color(60, 60, 60));

                // 按钮样式
                btnBack.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
                btnBack.setBackground(new java.awt.Color(103, 58, 183)); // 深紫色
                btnBack.setForeground(java.awt.Color.WHITE);
                btnBack.setFocusPainted(false);
                btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));

                // 表格样式
                tblDonations.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
                tblDonations.setRowHeight(28);
                tblDonations.setGridColor(new java.awt.Color(200, 190, 230)); // 淡紫灰
                tblDonations.setForeground(new java.awt.Color(33, 33, 33));
                tblDonations.setSelectionBackground(new java.awt.Color(190, 170, 240));
                tblDonations.setSelectionForeground(java.awt.Color.WHITE);

                tblDonations.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
                tblDonations.getTableHeader().setBackground(new java.awt.Color(230, 225, 250));
                tblDonations.getTableHeader().setForeground(new java.awt.Color(54, 33, 89));

                jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE); // 保证滚动区域干净
        }

}
