/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminWorkArea;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.FoodEnterprise;
import model.FoodShelterSystem.FoodShelterSystem;
import model.NetWork.NetWork;
import model.Organization.FoodIncOrg;
import model.Role.FoodEnterpriseManager;

/**
 *
 * @author sylvia
 */
public class AddFoodOrgPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddFoodOrgPanel
     */
    
    JPanel workArea;
    UserAccount account;
    FoodShelterSystem foodShelterSystem;
    NetWork netWork;
    AdminWorkAreaPanel parent;
    
    public AddFoodOrgPanel(JPanel workArea, UserAccount account, FoodShelterSystem foodShelterSystem, AdminWorkAreaPanel parent) {
        this.workArea = workArea;
        this.account = account;
        this.foodShelterSystem = foodShelterSystem;
        this.parent = parent;
        
        initComponents();
        //set the orgnziation ID in the label. 
        FoodIncOrg preview = new FoodIncOrg("new");
        txtOrgID.setText(String.valueOf(preview.getOrganizationID()));
        
        
        populateAdminComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtOrgName = new javax.swing.JTextField();
        lblConfirmPassword = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtOrgID = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        lbluserName = new javax.swing.JLabel();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Add Food Organization");

        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtOrgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgNameActionPerformed(evt);
            }
        });

        lblConfirmPassword.setText("Location");

        txtOrgID.setEditable(false);
        txtOrgID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgIDActionPerformed(evt);
            }
        });

        lblpassword.setText("Organization Name");

        lbluserName.setText("Organization ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnBack)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbluserName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOrgName)
                            .addComponent(txtLocation)
                            .addComponent(txtOrgID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(enterpriseLabel)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbluserName)
                            .addComponent(txtOrgID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpassword)
                            .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConfirmPassword)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
       String organizationName = txtOrgName.getText().trim();
       String location = txtLocation.getText().trim();
       
        UserAccount selectedAdmin = (UserAccount) jComboBox1.getSelectedItem();                
        
        if (organizationName.isEmpty()|| location.isEmpty()||jComboBox1.getSelectedItem()== null)
        {
            JOptionPane.showMessageDialog(this, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        FoodIncOrg newOrg = new FoodIncOrg(organizationName);
        newOrg.setAddress(location);
        
        FoodEnterprise foodEnterprise = null;
        
        for(NetWork netWork:foodShelterSystem.getNetworkList()){
            for (BasicEnterprise be:netWork.getEnterpriseDirectory().getEnterprises()){
                if (be instanceof FoodEnterprise){
                    foodEnterprise = (FoodEnterprise)be;
                    break;
                }
                
            }
            
        }
        
        if (foodEnterprise == null){
            JOptionPane.showMessageDialog(this, "No FoodEnterprise found in system.");
            return;
        }
        
        foodEnterprise.getOrganizationDirectory().getOrganizationList().add(newOrg);

        selectedAdmin.setOrganization(newOrg);
        selectedAdmin.setRole(new FoodEnterpriseManager());
        
        JOptionPane.showMessageDialog(this, "Organization created successfully!\nID: " + newOrg.getOrganizationID());

        txtOrgName.setText("");
        txtLocation.setText("");
        jComboBox1.setSelectedIndex(0);
        txtOrgID.setText(String.valueOf(new FoodIncOrg("new").getOrganizationID()));
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.show(workArea,"AdminWorkAreaPanel");
        parent.populateTable();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtOrgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgNameActionPerformed

    private void txtOrgIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbluserName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtOrgID;
    private javax.swing.JTextField txtOrgName;
    // End of variables declaration//GEN-END:variables

    private void populateAdminComboBox() {


        jComboBox1.removeAllItems();

        for (NetWork net : foodShelterSystem.getNetworkList()) {
            for (BasicEnterprise be : net.getEnterpriseDirectory().getEnterprises()) {
                if (be instanceof FoodEnterprise) {
                    for (UserAccount ua : be.getUserAccountDirectory().getUserAccountList()) {
                        if (ua.getRole() != null && ua.getRole().getClass().getSimpleName().equals("FoodOrgAdmin")) {
                            jComboBox1.addItem(ua.toString());
                        }
                    }
                }
            }
        }


    }
    
}
