/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminWorkArea;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.FoodEnterprise;
import model.Enterprise.VolunteerEnterprise;
import model.FoodShelterSystem.FoodShelterSystem;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.DriverOrg;
import model.Organization.FoodIncOrg;
import model.Role.FoodEnterpriseManager;

/**
 *
 * @author sylvia
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaPanel
     */
    
    JPanel workArea;
    UserAccount account;
    FoodShelterSystem foodShelterSystem;
    NetWork netWork;
    AdminWorkAreaPanel parent;
    
    public AdminWorkAreaPanel(JPanel workArea, UserAccount account, FoodShelterSystem foodShelterSystem) {
        this.workArea = workArea;
        this.account = account;
        this.foodShelterSystem = foodShelterSystem;
        
        initComponents();
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Manage Food Organizations");

        jLabel1.setText("Only used to manage food donation organizations.");

        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Organization ID", "Name", "Location", "Admin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblOrg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int selectedRow = tblOrg.getSelectedRow();
        
        if (selectedRow <0){
            JOptionPane.showMessageDialog(this, "Please select a organization to delete", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this organization?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        int orgID = (int) tblOrg.getValueAt(selectedRow, 0);

        for (NetWork net : foodShelterSystem.getNetworkList()) {
            for (BasicEnterprise be : net.getEnterpriseDirectory().getEnterprises()) {
                if (be instanceof FoodEnterprise) {                    
                    ArrayList<BasicOrganization> orgList = be.getOrganizationDirectory().getOrganizationList();
                    for (int i = 0; i < orgList.size(); i++) {
                        BasicOrganization org = orgList.get(i);
                        if (org instanceof FoodIncOrg && ((FoodIncOrg) org).getOrganizationID() == orgID) {
                            orgList.remove(i); 
                            break;
                        }
                    }

                   ArrayList<UserAccount> uaList = be.getUserAccountDirectory().getUserAccountList();
                    for (int i = 0; i < uaList.size(); i++) {
                        UserAccount ua = uaList.get(i);
                        if (ua.getOrganization() != null
                                && ua.getOrganization() instanceof FoodIncOrg
                                && ((FoodIncOrg) ua.getOrganization()).getOrganizationID() == orgID) {
                            uaList.remove(i); 
                            break;
                        }
                    }

                    populateTable();
                    JOptionPane.showMessageDialog(this, "Organization deleted successfully.");
                    return;
                }
            }
        }     
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) workArea.getLayout();
        workArea.add("AddFoodOrgPanel", new AddFoodOrgPanel(workArea, account, foodShelterSystem, this));
        layout.show(workArea,"AddFoodOrgPanel");
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblOrg;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblOrg.getModel();
        model.setRowCount(0);  

        for (NetWork net : foodShelterSystem.getNetworkList()) {
            for (BasicEnterprise be : net.getEnterpriseDirectory().getEnterprises()) {
                if (be instanceof FoodEnterprise) {
                    for (BasicOrganization org : be.getOrganizationDirectory().getOrganizationList()) {
                        if (org instanceof FoodIncOrg) {
                            FoodIncOrg foodOrg = (FoodIncOrg) org;

                            // Find assigned admin
                            UserAccount admin = null;
                            for (UserAccount ua : be.getUserAccountDirectory().getUserAccountList()) {
                                if (ua.getOrganization() == foodOrg && ua.getRole() instanceof FoodEnterpriseManager) {
                                    admin = ua;
                                    break;
                                }
                            }

                            Object[] row = new Object[4];
                            row[0] = foodOrg.getOrganizationID();
                            row[1] = foodOrg.getName();
                            row[2] = foodOrg.getAddress();
                            row[3] = (admin != null) ? admin.getUsername() : "N/A";

                            model.addRow(row);
                        }
                    }
                }
            }
        }
    }

        
        
        

    
    
    
}
