/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminWorkArea;

import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.FoodItem.FoodItem;
import model.FoodShelterSystem.FoodShelterSystem;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.WorkQueue.WorkQueue;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestFoodItem;

/**
 *
 * @author 59386
 */
public class viewNetWorkDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewNetWorkDetailPanel
     */
    NetWork netWork;
    JPanel workArea;
    FoodShelterSystem system;
    UserAccount account;

    public viewNetWorkDetailPanel(JPanel workArJPanel, NetWork netWork, FoodShelterSystem system, UserAccount account) {
        initComponents();
        this.workArea = workArJPanel;
        this.netWork = netWork;
        this.account = account;
        this.system = system;
        populateUserAccountTable();
    }

    @Override
    public Graphics getGraphics() {
        return super.getGraphics(); // Generated from
                                    // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    public viewNetWorkDetailPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tbUserAccount = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();

        tbUserAccount.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Entrprise", "Org", "UUID", "Name", "Role"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbUserAccount);
        if (tbUserAccount.getColumnModel().getColumnCount() > 0) {
            tbUserAccount.getColumnModel().getColumn(4).setHeaderValue("Role");
        }

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NetWork UserAccount Table");

        BtnBack.setText("<< back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 813,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(BtnBack)
                                                .addGap(80, 80, 80)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(110, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(BtnBack))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 478,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(122, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnBackActionPerformed

        AdminStartPoint adminStartPoint = new AdminStartPoint(workArea, account, system);
        workArea.add("AdminStartPoint", adminStartPoint);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "AdminStartPoint");
        workArea.revalidate();
        workArea.repaint();
    }// GEN-LAST:event_BtnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbUserAccount;

    // End of variables declaration//GEN-END:variables
    ///////////////////////////////////////////// fun ////////////////////
    public void populateUserAccountTable() {
        DefaultTableModel model = (DefaultTableModel) tbUserAccount.getModel();
        model.setRowCount(0);
        // 从userAccount的workQueue中获得

        for (UserAccount ua : netWork.getUserAccountDirctory().getUserAccountList()) {
            Object row[] = new Object[5];
            if (ua.getEnterprise() != null) {
                row[0] = ua.getEnterprise().getName();
            } else {
                row[0] = "null";
            }
            if (ua.getOrganization() != null) {
                row[1] = ua.getOrganization().getName();
            }
            row[2] = ua.getAccountUuid();
            row[3] = ua.getUsername();
            String fullName = ua.getRole().getClass().getName();
            String[] parts = fullName.split("\\.");
            String roleName = parts[parts.length - 1];
            row[4] = roleName;
            model.addRow(row);
        }
    }

}
