/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RescueNetAdminWorkArea;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.NetWork.NetWork;
import model.Organization.RequestCollectOrg;
import model.Role.Homeless;
import utils.IsMatch;

/**
 *
 * @author yuewu
 */
public class AddHomelessAccount extends javax.swing.JPanel {
    private BasicEnterprise enterprise;
    private RequestCollectOrg requestCollectOrg;
    private UserAccount account;
    private NetWork netWork;
    private UserAccount oldUserAccount;
    JPanel workArea;
    String InconPath;

    /**
     * Creates new form NewJPanel
     */
    public AddHomelessAccount(JPanel workArea,UserAccount account, NetWork netWork,BasicEnterprise enterprise, RequestCollectOrg org, UserAccount oldAccount) {
        initComponents();
        this.enterprise = enterprise;
        this.requestCollectOrg = org;
        this.InconPath ="";
        this.account = account;
        this.netWork = netWork;
        this.workArea = workArea;
        this.oldUserAccount = oldAccount;
        if(oldUserAccount==null){
            btnSubmit.setEnabled(true);
            btnUpdate.setEnabled(false);
        }else{
            btnSubmit.setEnabled(false);
            btnUpdate.setEnabled(true);
            PopulateTxt();
        }
        beautify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        txtuserName = new javax.swing.JTextField();
        lbluserName = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        IncoLabel = new javax.swing.JLabel();
        btnSelectImg = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnUpdate = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Add New User - Homeless");

        lbluserName.setText("User Name");

        lblpassword.setText("Password");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        lblEmail.setText("Email");

        lbPhone.setText("Phone");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnSelectImg.setText("select an Image");
        btnSelectImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImgActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBack)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblEmail)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbPhone)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblpassword)
                                    .addGap(18, 18, 18)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbluserName)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtuserName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(btnSubmit)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IncoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(btnSelectImg)))
                                .addContainerGap(265, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtuserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbluserName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpassword))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPhone)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(IncoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSelectImg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnUpdate))
                .addContainerGap(373, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String username = txtuserName.getText();
        String password = String.valueOf(passwordField.getPassword());
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        
        IsMatch isMatch = new IsMatch();
        if(isMatch.isEmailMatch(email)&&isMatch.isNameMatch(username)){
            JOptionPane.showMessageDialog(this, "name or email validation error");
            return;
        }
        if (username.isEmpty() || password.isEmpty() || email.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }
        if (!requestCollectOrg.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            JOptionPane.showMessageDialog(this, "Username already exists.");
            return;
        }

        Homeless role = (Homeless) oldUserAccount.getRole();
        if(this.InconPath!=null && !this.InconPath.equals("")){
            role.setInconPath(InconPath);
        }else{
            role.setInconPath(null);
        }
        
        oldUserAccount.setEmail(email);
        oldUserAccount.setPhone(phone);
        oldUserAccount.setUsername(username);

        JOptionPane.showMessageDialog(this, "update successfully!");

        txtuserName.setText("");
        passwordField.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSelectImgActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSelectImgActionPerformed
        // TODO add your handling code here:
        // 1. using JFileChooser to choose img and limit file type
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("upload homeless' incon（Img only） ");
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg", "gif");
        fileChooser.addChoosableFileFilter(filter);
        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                // 1. 保存图片到本地目录
                String targetDirPath = "uploadedImages";
                File dir = new File(targetDirPath);
                if (!dir.exists())
                    dir.mkdir();

                File destinationFile = new File(dir, selectedFile.getName());
                Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

                // 2. 显示图片
                ImageIcon imageIcon = new ImageIcon(destinationFile.getAbsolutePath());
                Image image = imageIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                IncoLabel.setIcon(new ImageIcon(image));
                this.InconPath = destinationFile.getAbsolutePath();

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error uploading image: " + e.getMessage());
            }
        }

    }// GEN-LAST:event_btnSelectImgActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        HomelessAdmin homelessAdmin = new HomelessAdmin(workArea, account, this.requestCollectOrg, enterprise, netWork);
        workArea.add("HomelessAdmin",homelessAdmin);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "HomelessAdmin");
    }// GEN-LAST:event_btnBackActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordFieldActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String username = txtuserName.getText();
        String password = String.valueOf(passwordField.getPassword());
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        
        IsMatch isMatch = new IsMatch();
        if(isMatch.isEmailMatch(email)&&isMatch.isNameMatch(username)){
            JOptionPane.showMessageDialog(this, "name or email validation error");
            return;
        }
        if (username.isEmpty() || password.isEmpty() || email.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }
        if (!requestCollectOrg.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            JOptionPane.showMessageDialog(this, "Username already exists.");
            return;
        }

        Homeless role = new Homeless();
        if(this.InconPath!=null && !this.InconPath.equals("")){
            role.setInconPath(InconPath);
        }else{
            role.setInconPath(null);
        }
        

        UserAccount account = netWork.getUserAccountDirctory().createUserAccount(username, password, role);
        requestCollectOrg.getUserAccountDirectory().getUserAccountList().add(account);
        account.setEmail(email);
        account.setPhone(phone);
        account.setOrganization(requestCollectOrg);
        account.setEnterprise(this.enterprise);

        JOptionPane.showMessageDialog(this, "New homeless user created successfully!");

        txtuserName.setText("");
        passwordField.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
    }// GEN-LAST:event_btnSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IncoLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSelectImg;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbluserName;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtuserName;
    // End of variables declaration//GEN-END:variables

    
    // pupolate Text field
    private void PopulateTxt(){
        txtuserName.setText(oldUserAccount.getUsername());
        txtEmail.setText(oldUserAccount.getEmail());
        txtPhone.setText(oldUserAccount.getPhone());
        passwordField.setText(oldUserAccount.getPassword());
        Homeless homeless = (Homeless) oldUserAccount.getRole();
        ImageIcon imageIcon = new ImageIcon(homeless.getInconPath());
        Image image = imageIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        IncoLabel.setIcon(new ImageIcon(image));
    }
    
    //
    private void beautify() {
        // 背景
        this.setBackground(new java.awt.Color(245, 242, 250)); // 淡紫灰背景

        // 标题
        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        enterpriseLabel.setForeground(new java.awt.Color(54, 33, 89)); // 深紫

        // 标签字体统一
        java.awt.Font labelFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
        java.awt.Color labelColor = new java.awt.Color(80, 80, 80);

        lbluserName.setFont(labelFont);
        lbluserName.setForeground(labelColor);

        lblpassword.setFont(labelFont);
        lblpassword.setForeground(labelColor);

        lblEmail.setFont(labelFont);
        lblEmail.setForeground(labelColor);

        lbPhone.setFont(labelFont);
        lbPhone.setForeground(labelColor);

        // 输入框样式
        javax.swing.JTextField[] textFields = { txtuserName, txtEmail, txtPhone };
        for (javax.swing.JTextField field : textFields) {
            field.setFont(labelFont);
            field.setBackground(java.awt.Color.WHITE);
            field.setForeground(new java.awt.Color(40, 40, 40));
            field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));
        }

        // 密码框
        passwordField.setFont(labelFont);
        passwordField.setBackground(java.awt.Color.WHITE);
        passwordField.setForeground(new java.awt.Color(40, 40, 40));
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));

        // 按钮样式
        javax.swing.JButton[] buttons = { btnBack, btnSubmit,btnUpdate };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(labelFont);
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }
    }

}
