/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RescueNetAdminWorkArea;

import javax.swing.JOptionPane;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Organization.RequestCollectOrg;
import model.Role.Homeless;

/**
 *
 * @author yuewu
 */
public class AddHomelessAccount extends javax.swing.JPanel {
    private BasicEnterprise enterprise;
    private RequestCollectOrg requestCollectOrg;

    /**
     * Creates new form NewJPanel
     */
    public AddHomelessAccount(BasicEnterprise enterprise, RequestCollectOrg org) {
        initComponents();
        this.enterprise = enterprise;
        this.requestCollectOrg = org;
        beautify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        txtuserName = new javax.swing.JTextField();
        lbluserName = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Add New User - Homeless");

        lbluserName.setText("User Name");

        lblpassword.setText("Password");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        lblEmail.setText("Email");

        lbPhone.setText("Phone");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnBack)
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(btnSubmit)
                                                                .addGap(64, 64, 64))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(lblEmail)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtEmail,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 155,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(lbPhone)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtPhone,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 155,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(lblpassword)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(passwordField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 155,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(lbluserName)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtuserName,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 155,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(enterpriseLabel))
                                .addContainerGap(626, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBack)
                                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtuserName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbluserName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblpassword))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEmail))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbPhone))
                                .addGap(29, 29, 29)
                                .addComponent(btnSubmit)
                                .addContainerGap(384, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnBackActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordFieldActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String username = txtuserName.getText();
        String password = String.valueOf(passwordField.getPassword());
        String email = txtEmail.getText();
        String phone = txtPhone.getText();

        if (username.isEmpty() || password.isEmpty() || email.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (!requestCollectOrg.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            JOptionPane.showMessageDialog(this, "Username already exists.");
            return;
        }

        Homeless role = new Homeless();

        UserAccount account = requestCollectOrg.getUserAccountDirectory().createUserAccount(username, password, role);

        account.setEmail(email);
        account.setPhone(phone);
        account.setOrganization(requestCollectOrg);

        JOptionPane.showMessageDialog(this, "New homeless user created successfully!");

        txtuserName.setText("");
        passwordField.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
    }// GEN-LAST:event_btnSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbluserName;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtuserName;
    // End of variables declaration//GEN-END:variables

    //
    private void beautify() {
        // 背景
        this.setBackground(new java.awt.Color(245, 242, 250)); // 淡紫灰背景

        // 标题
        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        enterpriseLabel.setForeground(new java.awt.Color(54, 33, 89)); // 深紫

        // 标签字体统一
        java.awt.Font labelFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
        java.awt.Color labelColor = new java.awt.Color(80, 80, 80);

        lbluserName.setFont(labelFont);
        lbluserName.setForeground(labelColor);

        lblpassword.setFont(labelFont);
        lblpassword.setForeground(labelColor);

        lblEmail.setFont(labelFont);
        lblEmail.setForeground(labelColor);

        lbPhone.setFont(labelFont);
        lbPhone.setForeground(labelColor);

        // 输入框样式
        javax.swing.JTextField[] textFields = { txtuserName, txtEmail, txtPhone };
        for (javax.swing.JTextField field : textFields) {
            field.setFont(labelFont);
            field.setBackground(java.awt.Color.WHITE);
            field.setForeground(new java.awt.Color(40, 40, 40));
            field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));
        }

        // 密码框
        passwordField.setFont(labelFont);
        passwordField.setBackground(java.awt.Color.WHITE);
        passwordField.setForeground(new java.awt.Color(40, 40, 40));
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));

        // 按钮样式
        javax.swing.JButton[] buttons = { btnBack, btnSubmit };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(labelFont);
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }
    }

}
