/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RescueNetAdminWorkArea;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.RescueNetEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.RequestCollectOrg;
import model.Role.Homeless;
import utils.PanelUtils;

/**
 *
 * @author yuewu
 */
public class HomelessAdmin extends javax.swing.JPanel {

    /**
     * Creates new form HomelessAdmin
     */
    JPanel workArea;
    NetWork netWork;
    RequestCollectOrg requestCollectOrg;
    RescueNetEnterprise rescueNetEnterprise;
    UserAccount account;

    public HomelessAdmin(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.netWork = netWork;
        this.requestCollectOrg = (RequestCollectOrg) organization;
        this.rescueNetEnterprise = (RescueNetEnterprise) enterprise;
        this.account = account;
        initComponents();
        populateTable();
        beautify();

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblHomeless.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblHomeless.setRowSorter(sorter);
        model.setRowCount(0);

        int count = 1;
        for (UserAccount ua : requestCollectOrg.getUserAccountDirectory().getUserAccountList()) {
            Object[] row = new Object[3];
            row[0] = count++;
            row[1] = ua;
            row[2] = ua.getPhone();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        accountLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHomeless = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        InconLabel = new javax.swing.JLabel();
        btnShowIncon = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        accountLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accountLabel.setText("Homeless Admin - Account Management");

        tblHomeless.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Homeless ID", "Name", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblHomeless);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnShowIncon.setText("show Incon");
        btnShowIncon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowInconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnShowIncon)
                        .addGap(344, 344, 344)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(48, 48, 48)
                                .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InconLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd)
                    .addComponent(btnShowIncon))
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowInconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowInconActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHomeless.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row first.");
            return;
        }
        String filePath = null;
        UserAccount account = (UserAccount) tblHomeless.getValueAt(selectedRow, 1);
        Homeless homeless = (Homeless) account.getRole();
        filePath = homeless.getInconPath();
        if(filePath!=null && !filePath.equals("")){
            ImageIcon imageIcon = new ImageIcon(filePath);
            Image image = imageIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            InconLabel.setIcon(new ImageIcon(image));
        }else{
            JOptionPane.showMessageDialog(this, "this one does not have Incon yet");
        }
    }//GEN-LAST:event_btnShowInconActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backJButtonActionPerformed
        //todo
        RescueNetAdminStartPoint rescueNetAdminStartPoint = new RescueNetAdminStartPoint(workArea, account, requestCollectOrg,
                rescueNetEnterprise, netWork);
        PanelUtils.addOrReplacePanel(workArea, "RescueNetAdminStartPoint", rescueNetAdminStartPoint);
        workArea.add("RescueNetAdminStartPoint", rescueNetAdminStartPoint);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "RescueNetAdminStartPoint");
        
    }// GEN-LAST:event_backJButtonActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddHomelessAccount panel = new AddHomelessAccount(workArea,account, netWork, rescueNetEnterprise, requestCollectOrg);
        workArea.add("AddHomelessAccount", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea,"AddHomelessAccount");
    }// GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHomeless.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        UserAccount account = (UserAccount) tblHomeless.getValueAt(selectedRow, 1);
        this.requestCollectOrg.getUserAccountDirectory().getUserAccountList().remove(account);
        this.netWork.getUserAccountDirctory().getUserAccountList().remove(account);
        populateTable();
    }// GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InconLabel;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnShowIncon;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblHomeless;
    // End of variables declaration//GEN-END:variables

    private void beautify() {
        // 背景
        this.setBackground(new java.awt.Color(245, 242, 250)); // 淡紫灰

        // 标题样式
        accountLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        accountLabel.setForeground(new java.awt.Color(54, 33, 89)); // 深紫标题

        // 按钮美化
        javax.swing.JButton[] buttons = { backJButton, btnAdd, btnDelete };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫按钮
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }

        // 表格样式
        tblHomeless.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        tblHomeless.setRowHeight(28);
        tblHomeless.setGridColor(new java.awt.Color(200, 190, 230)); // 紫灰边框
        tblHomeless.setForeground(new java.awt.Color(33, 33, 33));
        tblHomeless.setSelectionBackground(new java.awt.Color(190, 170, 240));
        tblHomeless.setSelectionForeground(java.awt.Color.WHITE);

        tblHomeless.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        tblHomeless.getTableHeader().setBackground(new java.awt.Color(230, 225, 250));
        tblHomeless.getTableHeader().setForeground(new java.awt.Color(54, 33, 89));

        jScrollPane3.getViewport().setBackground(java.awt.Color.WHITE);
    }

}
