/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RescueNetAdminWorkArea;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.RequestCollectOrg;
import model.Organization.RequestEntertainOrg;

/**
 *
 * @author sylvia
 */
public class RescueNetAdminStartPoint extends javax.swing.JPanel {
    private JPanel workArea;
    private UserAccount account;
    private BasicEnterprise enterprise;
    private NetWork netWork;
    private RequestEntertainOrg requestEntertainOrg;
    private RequestCollectOrg requestCollectOrg;

    /**
     * Creates new form RescueNetAdminStartPoint
     */
    public RescueNetAdminStartPoint(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        initComponents();
        this.workArea = workArea;
        this.account = account;
        this.enterprise = enterprise;
        this.netWork = netWork;

        if (organization instanceof RequestEntertainOrg) {
            this.requestEntertainOrg = (RequestEntertainOrg) organization;
        } else if (organization instanceof RequestCollectOrg) {
            this.requestCollectOrg = (RequestCollectOrg) organization;
        }

        jLabel1.setText("Welcome, " + account.getUsername());
        jLabel2.setText("Enterprise: " + enterprise.getName());
        beautify();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnShelter = new javax.swing.JButton();
        btnHomeless = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Welcome, <value>");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Enterprise: < >");

        btnShelter.setText("Manage Shelter Helper");
        btnShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShelterActionPerformed(evt);
            }
        });

        btnHomeless.setText("Manage Homeless");
        btnHomeless.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomelessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(151, 151, 151)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnHomeless)
                                                        .addComponent(btnShelter))))
                                .addContainerGap(659, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addGap(67, 67, 67)
                                .addComponent(btnShelter)
                                .addGap(35, 35, 35)
                                .addComponent(btnHomeless)
                                .addContainerGap(534, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void btnShelterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnShelterActionPerformed
        // TODO add your handling code here:
        ShelterHelperAdmin panel = new ShelterHelperAdmin(workArea, account, requestEntertainOrg, enterprise, netWork);
        workArea.add("ShelterHelperAdmin", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }// GEN-LAST:event_btnShelterActionPerformed

    private void btnHomelessActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHomelessActionPerformed
        // TODO add your handling code here:
        HomelessAdmin panel = new HomelessAdmin(workArea, account, requestCollectOrg, enterprise, netWork);
        workArea.add("HomelessAdmin", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }// GEN-LAST:event_btnHomelessActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomeless;
    private javax.swing.JButton btnShelter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;

    // End of variables declaration//GEN-END:variables
    private void beautify() {
        // 主 Panel 背景统一
        this.setBackground(new java.awt.Color(245, 242, 250));
        jPanel1.setBackground(new java.awt.Color(245, 242, 250));

        // 欢迎标题字体
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        jLabel1.setForeground(new java.awt.Color(54, 33, 89)); // 深紫

        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        jLabel2.setForeground(new java.awt.Color(80, 80, 80)); // 深灰

        // 按钮样式统一
        javax.swing.JButton[] buttons = { btnHomeless, btnShelter };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫按钮
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }
    }

}
