/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RescueNetAdminWorkArea;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.RescueNetEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.RequestEntertainOrg;

/**
 *
 * @author yuewu
 */
public class ShelterHelperAdmin extends javax.swing.JPanel {

    /**
     * Creates new form ShelterHelperAdmin
     */
    JPanel workArea;
    RequestEntertainOrg requestEntertainOrg;
    NetWork netWork;
    RescueNetEnterprise rescueNetEnterprise;
    private BasicEnterprise enterprise;

    public ShelterHelperAdmin(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.requestEntertainOrg = (RequestEntertainOrg) organization;
        this.netWork = netWork;
        this.rescueNetEnterprise = (RescueNetEnterprise) enterprise;
        this.enterprise = enterprise;

        initComponents();
        populateTable();
        beautify();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblShelterHelper.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblShelterHelper.setRowSorter(sorter);
        model.setRowCount(0);

        int count = 1;
        for (UserAccount ua : requestEntertainOrg.getUserAccountDirectory().getUserAccountList()) {
            Object[] row = new Object[3];
            row[0] = count++;
            row[1] = ua.getUsername();
            row[2] = ua.getPhone();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        accountLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblShelterHelper = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        accountLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accountLabel.setText("Shelter Helper Admin - Account Management");

        tblShelterHelper.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null },
                        { null, null, null },
                        { null, null, null },
                        { null, null, null }
                },
                new String[] {
                        "Shelter Helper ID", "Name", "Contact"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblShelterHelper);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 423,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(backJButton)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(303, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete)
                                .addGap(336, 336, 336)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(backJButton)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAdd)
                                        .addComponent(btnDelete))
                                .addContainerGap(361, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backJButtonActionPerformed

    }// GEN-LAST:event_backJButtonActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddShelterHelper panel = new AddShelterHelper(enterprise, requestEntertainOrg);
        workArea.add("AddShelterHelper", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }// GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblShelterHelper.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        String username = (String) tblShelterHelper.getValueAt(selectedRow, 0);

        UserAccount toRemove = null;
        for (UserAccount ua : requestEntertainOrg.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getUsername().equals(username)) {
                toRemove = ua;
                break;
            }
        }

        if (toRemove != null) {
            requestEntertainOrg.getUserAccountDirectory().getUserAccountList().remove(toRemove);
            JOptionPane.showMessageDialog(this, "User deleted.");
            populateTable();
        }
    }// GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblShelterHelper;

    // End of variables declaration//GEN-END:variables
    private void beautify() {
        // 背景统一
        this.setBackground(new java.awt.Color(245, 242, 250));

        // 主标题样式
        accountLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        accountLabel.setForeground(new java.awt.Color(54, 33, 89)); // 深紫

        // 按钮美化
        javax.swing.JButton[] buttons = { backJButton, btnAdd, btnDelete };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫按钮
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }

        // 表格美化
        tblShelterHelper.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        tblShelterHelper.setRowHeight(28);
        tblShelterHelper.setGridColor(new java.awt.Color(200, 190, 230)); // 紫灰网格
        tblShelterHelper.setForeground(new java.awt.Color(33, 33, 33));
        tblShelterHelper.setSelectionBackground(new java.awt.Color(190, 170, 240));
        tblShelterHelper.setSelectionForeground(java.awt.Color.WHITE);

        tblShelterHelper.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        tblShelterHelper.getTableHeader().setBackground(new java.awt.Color(230, 225, 250));
        tblShelterHelper.getTableHeader().setForeground(new java.awt.Color(54, 33, 89));

        jScrollPane3.getViewport().setBackground(java.awt.Color.WHITE);
    }

}
