/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShelterHelperWorkArea;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FoodItem.FoodItem;

import model.WorkQueue.DeliveryTask;
import model.WorkQueue.WorkRequest;

import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.RescueNetEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.RequestEntertainOrg;


/**
 *
 * @author sylvia
 */
public class ShelterHelperWorkPanel extends javax.swing.JPanel {
    
    private RequestEntertainOrg requestEntertainOrg;

    /**
     * Creates new form ShelterHelperWorkPanel
     */
    JPanel workArea;
    RescueNetEnterprise rescueNetEnterprise;
    NetWork netWork;
    public ShelterHelperWorkPanel(JPanel workArea, UserAccount account, BasicOrganization organization, BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.rescueNetEnterprise = (RescueNetEnterprise) enterprise;
        this.requestEntertainOrg = (RequestEntertainOrg) organization;
        this.netWork = netWork;
        

        initComponents();
        this.requestEntertainOrg = requestEntertainOrg;
        populateApprovedFoodTable(requestEntertainOrg.getFoodCatalog().getFoodCatalog());
        populateShelterRequestTable((List<WorkRequest>) requestEntertainOrg.getWorkQueue().getWorkRequestList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShelterRequests = new javax.swing.JTable();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblApprovedFoodTasks = new javax.swing.JTable();
        btnAssignTask = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Shelter Helper - Task Assignment");

        tblShelterRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Requested Food Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShelterRequests);

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel1.setText("Shelter Requests");

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseLabel2.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel2.setText("Approved Food Table");

        tblApprovedFoodTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Food ID", "Food Name", "Type", "Quantity", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblApprovedFoodTasks);

        btnAssignTask.setText("Assign Task");
        btnAssignTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTaskActionPerformed(evt);
            }
        });

        jLabel1.setText("备注（写完后删除）：shelter里的status：Pending/ Matched/ Delivered");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(enterpriseLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(95, 95, 95)
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(enterpriseLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnAssignTask)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton))
                .addGap(18, 18, 18)
                .addComponent(enterpriseLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(enterpriseLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAssignTask)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnAssignTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTaskActionPerformed
        // TODO add your handling code here:
    int foodRow = tblApprovedFoodTasks.getSelectedRow();
    int requestRow = tblShelterRequests.getSelectedRow();

    if (foodRow < 0 || requestRow < 0) {
        JOptionPane.showMessageDialog(null, "Please select one food item and one shelter request.");
        return;
    }

    DefaultTableModel foodModel = (DefaultTableModel) tblApprovedFoodTasks.getModel();
    DefaultTableModel requestModel = (DefaultTableModel) tblShelterRequests.getModel();

    FoodItem selectedFood = (FoodItem) foodModel.getValueAt(foodRow, 0);
    WorkRequest selectedRequest = (WorkRequest) requestModel.getValueAt(requestRow, 0);

     if (selectedRequest.getReceiver() == null) {
            JOptionPane.showMessageDialog(null, "This request has no receiver assigned.");
            return;
        }
    
    // DeliveryTask创建了！
    DeliveryTask task = new DeliveryTask();
    task.setFoodItem(selectedFood);
    task.setQuantity(selectedFood.getNumber());
    task.setFromLocation(selectedFood.getFoodIncOrg().getName());
    task.setToLocation("Shelter"); // 后面要记得改成 selectedRequest 的 source
    task.setSender(selectedRequest.getSender()); 
    task.setReceiver(null); 
    task.setStatus("Pending");

    selectedRequest.getReceiver().getWorkQueue().getWorkRequestList().add(task);

    selectedRequest.setStatus("Matched");

    JOptionPane.showMessageDialog(null, "Delivery Task Created Successfully.");

    populateApprovedFoodTable(requestEntertainOrg.getFoodCatalog().getFoodCatalog());
    populateShelterRequestTable(requestEntertainOrg.getWorkQueue().getWorkRequestList());

    }//GEN-LAST:event_btnAssignTaskActionPerformed

    private void populateApprovedFoodTable(List<FoodItem> approvedFoodList) {
    DefaultTableModel model = (DefaultTableModel) tblApprovedFoodTasks.getModel();
    model.setRowCount(0); 

    for (FoodItem food : approvedFoodList) {
        if ("accepted".equalsIgnoreCase(food.getCheckingStatus()) && "stored".equalsIgnoreCase(food.getUsingStatus())) {
            Object[] row = new Object[5];
            row[0] = food; 
            row[1] = food.getFoodName();
            row[2] = food.getFoodIncOrg().getName();// 这里报错是因为需要等FoodIncEmployee调用的addFoodItem
            row[3] = food.getNumber();
            row[4] = food.getExpiredDate();
            model.addRow(row);
        }
    }
}
    
    private void populateShelterRequestTable(List<WorkRequest> shelterRequestList) {
    DefaultTableModel model = (DefaultTableModel) tblShelterRequests.getModel();
    model.setRowCount(0); 

    for (WorkRequest request : shelterRequestList) {
        if ("Pending".equalsIgnoreCase(request.getStatus())) {
            Object[] row = new Object[3];
            row[0] = request; 
            row[1] = request.getMessage(); //这里需要修改，从food request panel来
            row[2] = request.getStatus();
            model.addRow(row);
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAssignTask;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblApprovedFoodTasks;
    private javax.swing.JTable tblShelterRequests;
    // End of variables declaration//GEN-END:variables
}
