/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShelterHelperWorkArea;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.FoodItem.FoodItem;

import model.WorkQueue.DeliveryTask;
import model.WorkQueue.WorkRequest;

import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.RescueNetEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.RequestCollectOrg;
import model.Organization.RequestEntertainOrg;
import model.WorkQueue.WorkQueue;
import model.WorkQueue.WorkRequestFoodItem;
import model.WorkQueue.WorkRequestNeeds;

/**
 *
 * @author sylvia
 */
public class ShelterHelperWorkPanel extends javax.swing.JPanel {
    /**
     * Creates new form ShelterHelperWorkPanel
     */
    JPanel workArea;
    RescueNetEnterprise rescueNetEnterprise;
    NetWork netWork;
    RequestEntertainOrg requestEntertainOrg;

    public ShelterHelperWorkPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.rescueNetEnterprise = (RescueNetEnterprise) enterprise;
        this.requestEntertainOrg = (RequestEntertainOrg) organization;
        this.netWork = netWork;
        initComponents();
        populateApprovedFoodTable();
        populateShelterRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShelterRequests = new javax.swing.JTable();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblApprovedFoodTasks = new javax.swing.JTable();
        btnAssignTask = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Shelter Helper - Task Assignment");

        tblShelterRequests.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null },
                        { null, null, null },
                        { null, null, null },
                        { null, null, null }
                },
                new String[] {
                        "Number", "Requested Vendor", "Status"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShelterRequests);

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel1.setText("Shelter Requests");

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseLabel2.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel2.setText("Approved Food Table");

        tblApprovedFoodTasks.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Number", "Food Name", "Vendor", "Quantity", "Expiry Date"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblApprovedFoodTasks);

        btnAssignTask.setText("Assign Task");
        btnAssignTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTaskActionPerformed(evt);
            }
        });

        jLabel1.setText("备注（写完后删除）：shelter里的status：Pending/ Matched/ Delivered");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 631,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 631,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(233, 233, 233)
                                                                .addComponent(enterpriseLabel2))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(171, 171, 171)
                                                                .addComponent(enterpriseLabel,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 301,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(135, 135, 135)
                                                .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(280, 280, 280)
                                                .addComponent(btnAssignTask))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(265, 265, 265)
                                                .addComponent(enterpriseLabel1)))
                                .addContainerGap(375, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(enterpriseLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addGap(33, 33, 33)
                                .addComponent(enterpriseLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAssignTask)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignTaskActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAssignTaskActionPerformed
        // TODO add your handling code here:
        int foodRow = tblApprovedFoodTasks.getSelectedRow();
        int requestRow = tblShelterRequests.getSelectedRow();

        if (foodRow < 0 || requestRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select one food item and one shelter request.");
            return;
        }

        DefaultTableModel foodModel = (DefaultTableModel) tblApprovedFoodTasks.getModel();
        DefaultTableModel requestModel = (DefaultTableModel) tblShelterRequests.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(foodModel);
        TableRowSorter<DefaultTableModel> sorter1 = new TableRowSorter<>(requestModel);
        tblApprovedFoodTasks.setRowSorter(sorter);
        tblShelterRequests.setRowSorter(sorter1);

        FoodItem selectedFood = (FoodItem) foodModel.getValueAt(foodRow, 0);
        WorkRequest selectedRequest = (WorkRequest) requestModel.getValueAt(requestRow, 0);

        // 创建配送任务
        DeliveryTask task = new DeliveryTask();
        task.setFoodItem(selectedFood);
        task.setQuantity(selectedFood.getNumber());
        task.setFromLocation(selectedFood.getFoodIncOrg().getName());
        task.setToLocation(selectedRequest.getSender().getName());
        task.setSender(requestEntertainOrg);
        task.setReceiver(selectedRequest.getSender()); // 接收者是请求的发送者
        task.setStatus("Pending"); // 初始状态为待处理

        // 将任务添加到请求发送者的工作队列
        selectedRequest.getSender().getWorkQueue().getWorkRequestList().add(task);

        // 将原请求状态更新为"已匹配"
        selectedRequest.setStatus("Matched");

        // 更新食品状态为"已分配"
        selectedFood.setUsingStatus("Assigned");

        JOptionPane.showMessageDialog(null, "Task assigned successfully!");

        // 刷新表格显示
        populateApprovedFoodTable();
        populateShelterRequestTable();
    }// GEN-LAST:event_btnAssignTaskActionPerformed

    private void populateApprovedFoodTable() {
        DefaultTableModel model = (DefaultTableModel) tblApprovedFoodTasks.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblApprovedFoodTasks.setRowSorter(sorter);
        model.setRowCount(0);

        // 从warehouseList来
        int index = 0;
        for (WorkRequest wr : netWork.getWarehouseList().getWorkRequestList()) {
            if (wr instanceof WorkRequestFoodItem) {
                WorkRequestFoodItem wrfi = (WorkRequestFoodItem) wr;
                FoodItem food = wrfi.getFoodItem();

                if (food != null) {
                    index++;
                    Object[] row = new Object[5];
                    row[0] = index;
                    row[1] = food.getFoodName();
                    row[2] = food.getFoodIncOrg().getName();
                    row[3] = food.getNumber();
                    row[4] = food.getExpiredDate();
                    model.addRow(row);
                }
            }
        }
    }

    private void populateShelterRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblShelterRequests.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblShelterRequests.setRowSorter(sorter);
        model.setRowCount(0);

        int index = 0;
        RequestCollectOrg org = rescueNetEnterprise.getRequestCollectOrg();
        WorkQueue queue = org.getWorkQueue();
        System.out.println("queue size :" + queue.getWorkRequestList().size());
        for (WorkRequest wr : queue.getWorkRequestList()) {
            WorkRequestNeeds wrn = (WorkRequestNeeds) wr;
            Object[] row = new Object[3];
            index++;
            row[0] = index;
            row[1] = wrn.getFoodOrgName();
            row[2] = wrn.getStatus();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignTask;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblApprovedFoodTasks;
    private javax.swing.JTable tblShelterRequests;
    // End of variables declaration//GEN-END:variables
}
