/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShelterHelperWorkArea;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.FoodItem.FoodItem;

import model.WorkQueue.DeliveryTask;
import model.WorkQueue.WorkRequest;

import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.RescueNetEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.RequestCollectOrg;
import model.Organization.RequestEntertainOrg;
import model.WorkQueue.WorkQueue;
import model.WorkQueue.WorkRequestFoodItem;
import model.WorkQueue.WorkRequestNeeds;

/**
 *
 * @author sylvia
 */
public class ShelterHelperWorkPanel extends javax.swing.JPanel {
    /**
     * Creates new form ShelterHelperWorkPanel
     */
    JPanel workArea;
    RescueNetEnterprise rescueNetEnterprise;
    NetWork netWork;
    RequestEntertainOrg requestEntertainOrg;

    public ShelterHelperWorkPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.rescueNetEnterprise = (RescueNetEnterprise) enterprise;
        this.requestEntertainOrg = (RequestEntertainOrg) organization;
        this.netWork = netWork;
        initComponents();
        populateApprovedFoodTable();
        populateShelterRequestTable();
        populateAssignedTasksTable();
        beautify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShelterRequests = new javax.swing.JTable();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblApprovedFoodTasks = new javax.swing.JTable();
        btnAssignTask = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAssignedTasks = new javax.swing.JTable();
        enterpriseLabel3 = new javax.swing.JLabel();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Shelter Helper - Task Assignment");

        tblShelterRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Number", "Requested Vendor", "Requested Quantity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShelterRequests);

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel1.setText("Shelter Requests");

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseLabel2.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterpriseLabel2.setText("Approved Food Table");

        tblApprovedFoodTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Number", "Food Name", "Vendor", "Quantity", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblApprovedFoodTasks);

        btnAssignTask.setText("Assign Task");
        btnAssignTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTaskActionPerformed(evt);
            }
        });

        tblAssignedTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Number", "Food Name", "Vendor", "Quantity"
            }
        ));
        jScrollPane4.setViewportView(tblAssignedTasks);

        jScrollPane3.setViewportView(jScrollPane4);

        enterpriseLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseLabel3.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel3.setText("Assigned Tasks");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(btnAssignTask))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(enterpriseLabel1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(enterpriseLabel2)
                        .addGap(297, 297, 297)
                        .addComponent(enterpriseLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(250, 770, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel2)
                    .addComponent(enterpriseLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(enterpriseLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAssignTask)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignTaskActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAssignTaskActionPerformed
        // TODO add your handling code here:
        int foodRow = tblApprovedFoodTasks.getSelectedRow();
    int requestRow = tblShelterRequests.getSelectedRow();

    if (foodRow < 0 || requestRow < 0) {
        JOptionPane.showMessageDialog(null, "Please select one food item and one shelter request.");
        return;
    }

    // Convert view indices to model indices
    int foodModelRow = tblApprovedFoodTasks.convertRowIndexToModel(foodRow);
    int requestModelRow = tblShelterRequests.convertRowIndexToModel(requestRow);

    DefaultTableModel foodModel = (DefaultTableModel) tblApprovedFoodTasks.getModel();
    DefaultTableModel requestModel = (DefaultTableModel) tblShelterRequests.getModel();


    WorkRequestFoodItem selectedFoodRequest = null;
    for (WorkRequest wr : netWork.getWarehouseList().getWorkRequestList()) {
        if (wr instanceof WorkRequestFoodItem) {
            WorkRequestFoodItem wrfi = (WorkRequestFoodItem) wr;
            FoodItem food = wrfi.getFoodItem();

            if (food != null && 
                food.getFoodName().equals(foodModel.getValueAt(foodModelRow, 1)) && 
                food.getFoodIncOrg().getName().equals(foodModel.getValueAt(foodModelRow, 2)) &&
                food.getNumber() == Integer.parseInt(foodModel.getValueAt(foodModelRow, 3).toString())) {
                selectedFoodRequest = wrfi;
                break;
            }
        }
    }

    WorkRequestNeeds selectedRequest = null;
    for (WorkRequest wr : rescueNetEnterprise.getRequestCollectOrg().getWorkQueue().getWorkRequestList()) {
        if (wr instanceof WorkRequestNeeds) {
            WorkRequestNeeds wrn = (WorkRequestNeeds) wr;
            // Match based on displayed properties
            if (wrn.getFoodOrgName().equals(requestModel.getValueAt(requestModelRow, 1)) &&
                wrn.getStatus().equals(requestModel.getValueAt(requestModelRow, 2))) {
                selectedRequest = wrn;
                break;
            }
        }
    }

    if (selectedFoodRequest == null || selectedRequest == null) {
        JOptionPane.showMessageDialog(null, "Could not identify the selected items. Please try again.");
        return;
    }

    FoodItem selectedFood = selectedFoodRequest.getFoodItem();

    DeliveryTask task = new DeliveryTask();
    task.setFoodItem(selectedFood);
    task.setQuantity(selectedFood.getNumber());
    task.setFromLocation(selectedFood.getFoodIncOrg().getName());
    task.setToLocation(selectedRequest.getSender().getName());
    task.setSender(requestEntertainOrg);
    task.setReceiver(selectedRequest.getSender());
    task.setStatus("Pending");

    selectedRequest.getSender().getWorkQueue().getWorkRequestList().add(task);

    selectedRequest.setStatus("Matched");

    selectedFood.setUsingStatus("Assigned");

    JOptionPane.showMessageDialog(null, "Task assigned successfully!");

    populateApprovedFoodTable();
    populateShelterRequestTable();
    populateAssignedTasksTable();
    }// GEN-LAST:event_btnAssignTaskActionPerformed

    private void populateApprovedFoodTable() {
       DefaultTableModel model = (DefaultTableModel) tblApprovedFoodTasks.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    tblApprovedFoodTasks.setRowSorter(sorter);
    model.setRowCount(0);

    int index = 0;
    for (WorkRequest wr : netWork.getWarehouseList().getWorkRequestList()) {
        if (wr instanceof WorkRequestFoodItem) {
            WorkRequestFoodItem wrfi = (WorkRequestFoodItem) wr;
            FoodItem food = wrfi.getFoodItem();

            if (food != null && !"Assigned".equals(food.getUsingStatus())) {
                index++;
                Object[] row = new Object[5];
                row[0] = index;
                row[1] = food.getFoodName();
                row[2] = food.getFoodIncOrg().getName();
                row[3] = food.getNumber();
                row[4] = food.getExpiredDate();
                model.addRow(row);
            }
        }
    }
    }

    private void populateShelterRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblShelterRequests.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    tblShelterRequests.setRowSorter(sorter);
    model.setRowCount(0);

    int index = 0;
    RequestCollectOrg org = rescueNetEnterprise.getRequestCollectOrg();
    WorkQueue queue = org.getWorkQueue();
    System.out.println("queue size :" + queue.getWorkRequestList().size());
    
    for (WorkRequest wr : queue.getWorkRequestList()) {
        if (wr instanceof WorkRequestNeeds) {
            WorkRequestNeeds wrn = (WorkRequestNeeds) wr;

            if ("pending".equalsIgnoreCase(wrn.getStatus())) {
                Object[] row = new Object[4];
                index++;
                row[0] = index;
                row[1] = wrn.getFoodOrgName();
                row[2] = wrn.getQuantity();
                row[3] = wrn.getStatus();
                model.addRow(row);
            }
        }
    }
    }
    
    private void populateAssignedTasksTable() {
    DefaultTableModel model = (DefaultTableModel) tblAssignedTasks.getModel();
    model.setRowCount(0);
    
    int index = 0;

    for (WorkRequest wr : requestEntertainOrg.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof DeliveryTask) {
            DeliveryTask task = (DeliveryTask) wr;
            FoodItem food = task.getFoodItem();
            
            if (food != null) {
                index++;
                Object[] row = new Object[4];
                row[0] = index;  // Auto-incremented number
                row[1] = food.getFoodName();
                row[2] = food.getFoodIncOrg().getName();
                row[3] = food.getNumber();
                model.addRow(row);
            }
        }
    }

    for (BasicOrganization org : rescueNetEnterprise.getOrganizationDirectory().getOrganizationList()) {
        for (WorkRequest wr : org.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof DeliveryTask) {
                DeliveryTask task = (DeliveryTask) wr;
                FoodItem food = task.getFoodItem();
                
                if (food != null) {
                    index++;
                    Object[] row = new Object[4];
                    row[0] = index;  // Auto-incremented number
                    row[1] = food.getFoodName();
                    row[2] = food.getFoodIncOrg().getName();
                    row[3] = food.getNumber();
                    model.addRow(row);
                }
            }
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignTask;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel enterpriseLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblApprovedFoodTasks;
    private javax.swing.JTable tblAssignedTasks;
    private javax.swing.JTable tblShelterRequests;
    // End of variables declaration//GEN-END:variables
    private void beautify() {
        // 背景统一
        this.setBackground(new java.awt.Color(245, 242, 250));
        jPanel1.setBackground(new java.awt.Color(245, 242, 250));

        // 标题字体
        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        enterpriseLabel.setForeground(new java.awt.Color(54, 33, 89)); // 深紫主标题

        // 分区小标题
        javax.swing.JLabel[] labels = { enterpriseLabel1, enterpriseLabel2 };
        for (javax.swing.JLabel label : labels) {
            label.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
            label.setForeground(new java.awt.Color(80, 80, 80)); // 灰紫色副标题
        }

        // 表格样式统一（两个表格）
        javax.swing.JTable[] tables = { tblApprovedFoodTasks, tblShelterRequests };
        for (javax.swing.JTable table : tables) {
            table.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
            table.setRowHeight(28);
            table.setGridColor(new java.awt.Color(200, 190, 230));
            table.setForeground(new java.awt.Color(33, 33, 33));
            table.setSelectionBackground(new java.awt.Color(190, 170, 240));
            table.setSelectionForeground(java.awt.Color.WHITE);

            table.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            table.getTableHeader().setBackground(new java.awt.Color(230, 225, 250));
            table.getTableHeader().setForeground(new java.awt.Color(54, 33, 89));
        }

        // 滚动面板背景白
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        jScrollPane2.getViewport().setBackground(java.awt.Color.WHITE);
        jScrollPane3.getViewport().setBackground(java.awt.Color.WHITE);
        jScrollPane4.getViewport().setBackground(java.awt.Color.WHITE);

        // 按钮样式
        btnAssignTask.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        btnAssignTask.setBackground(new java.awt.Color(103, 58, 183));
        btnAssignTask.setForeground(java.awt.Color.WHITE);
        btnAssignTask.setFocusPainted(false);
        btnAssignTask.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
    }

}
