/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FreshCheckWorkArea;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.FreshCheckEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.NewFoodCheckOrg;
import model.WorkQueue.*;

/**
 *
 * @author sylvia
 */
public class NewFoodCheckPanel extends javax.swing.JPanel {

    /**
     * Creates new form InspectorWorkPanel
     */
    NetWork netWork;
    NewFoodCheckOrg newFoodCheckOrg;
    FreshCheckEnterprise freshCheckEnterprise;
    JPanel workArea;
    UserAccount account;

    public NewFoodCheckPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.account = account;
        this.netWork = netWork;
        initComponents();
        if (enterprise instanceof FreshCheckEnterprise) {
            this.freshCheckEnterprise = (FreshCheckEnterprise) enterprise;
        }

        if (organization instanceof NewFoodCheckOrg) {
            this.newFoodCheckOrg = (NewFoodCheckOrg) organization;
        }

        // 最后填充表格
        populateTable();
        beautify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NewFoodTable = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("New Food Check");

        NewFoodTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Food ID", "Food Name", "Quantity", "Expiry Date", "Donor"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(NewFoodTable);

        btnApprove.setText("Accept");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(362, 362, 362)
                                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 682,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnApprove)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(btnReject)))))
                                .addGap(117, 195, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnReject)
                                        .addComponent(btnApprove))
                                .addGap(109, 109, 109)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int rowNumber = NewFoodTable.getSelectedRow();
        if (rowNumber < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row first");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) NewFoodTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        NewFoodTable.setRowSorter(sorter);
        int foodId = (int) model.getValueAt(rowNumber, 0); // 获取Food ID

        WorkRequestFoodItem selectedRequest = null;
        int count = 0;
        for (WorkRequest wd : netWork.getCheckList().getWorkRequestList()) {
            if (wd instanceof WorkRequestFoodItem) {
                count++;
                if (count == foodId) {
                    selectedRequest = (WorkRequestFoodItem) wd;
                    break;
                }
            }
        }
        if (selectedRequest != null) {
            selectedRequest.getFoodItem().setCheckingStatus("accepted");
            selectedRequest.getFoodItem().setUsingStatus("stored");

            // 从checkList移动到warehouseList
            netWork.getCheckList().removeWorkRequest(selectedRequest);
            netWork.getWarehouseList().getWorkRequestList().add(selectedRequest);

            JOptionPane.showMessageDialog(this, "Food item approved successfully!");
            populateTable();
        }

    }// GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int rowNumber = NewFoodTable.getSelectedRow();
        if (rowNumber < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row first");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) NewFoodTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        NewFoodTable.setRowSorter(sorter);
        int foodId = (int) model.getValueAt(rowNumber, 0); // 获取Food ID

        WorkRequestFoodItem selectedRequest = null;
        int count = 0;
        for (WorkRequest wd : netWork.getCheckList().getWorkRequestList()) {
            if (wd instanceof WorkRequestFoodItem) {
                count++;
                if (count == foodId) {
                    selectedRequest = (WorkRequestFoodItem) wd;
                    break;
                }
            }
        }

        if (selectedRequest != null) {
            netWork.getCheckList().removeWorkRequest(selectedRequest);

            populateTable();
        }
    }// GEN-LAST:event_btnRejectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable NewFoodTable;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    /////////// function////////////
    /// populize
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) NewFoodTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        NewFoodTable.setRowSorter(sorter);
        model.setRowCount(0);
        WorkQueue foodQueue = netWork.getCheckList();

        int count = 0;
        for (WorkRequest wd : foodQueue.getWorkRequestList()) {
            if (wd instanceof WorkRequestFoodItem) {
                WorkRequestFoodItem wrf = (WorkRequestFoodItem) wd;
                count++;
                Object row[] = new Object[5];
                row[0] = wrf;
                row[1] = wrf.getFoodItem().getFoodName();
                row[2] = wrf.getFoodItem().getNumber();
                row[3] = wrf.getFoodItem().getExpiredDate();
                row[4] = wrf.getFoodItem().getFoodIncOrg();

                model.addRow(row);
            }
        }

    }

    private void beautify() {
        // 背景色
        this.setBackground(new java.awt.Color(245, 242, 250));

        // 标题
        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        enterpriseLabel.setForeground(new java.awt.Color(54, 33, 89)); // 深紫

        // 按钮样式
        javax.swing.JButton[] buttons = { btnApprove, btnReject };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫按钮
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }

        // 表格样式
        NewFoodTable.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        NewFoodTable.setRowHeight(28);
        NewFoodTable.setGridColor(new java.awt.Color(200, 190, 230));
        NewFoodTable.setForeground(new java.awt.Color(33, 33, 33));
        NewFoodTable.setSelectionBackground(new java.awt.Color(190, 170, 240));
        NewFoodTable.setSelectionForeground(java.awt.Color.WHITE);

        NewFoodTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        NewFoodTable.getTableHeader().setBackground(new java.awt.Color(230, 225, 250));
        NewFoodTable.getTableHeader().setForeground(new java.awt.Color(54, 33, 89));

        jScrollPane2.getViewport().setBackground(java.awt.Color.WHITE);
    }

}
