/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FreshCheckWorkArea;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Enterprise.BasicEnterprise;
import model.Enterprise.FreshCheckEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.PushedFoodCheckOrg;
import model.WorkQueue.WorkQueue;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestDelivery;
import model.WorkQueue.WorkRequestFoodItem;

/**
 *
 * @author sylvia
 */
public class PostFoodCheckPanel extends javax.swing.JPanel {

    /**
     * Creates new form PostFoodCheckPanel
     */
    JPanel workArea;
    FreshCheckEnterprise freshCheckEnterprise;
    PushedFoodCheckOrg pushedFoodCheckOrg;
    NetWork netWork;

    public PostFoodCheckPanel(JPanel workArea, BasicEnterprise freshCheckEnterprise, BasicOrganization organization,
            NetWork netWork) {
        this.workArea = workArea;
        this.freshCheckEnterprise = (FreshCheckEnterprise) freshCheckEnterprise;
        this.netWork = netWork;
        if (netWork == null) {
            System.err.println("Panel get NetWork==null");
        } else
            System.err.println("Panel get NetWork!=null");
        if (organization instanceof PushedFoodCheckOrg) {
            this.pushedFoodCheckOrg = (PushedFoodCheckOrg) organization;
        }
        initComponents();
        populateTable();
        beautify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wareFoodTable = new javax.swing.JTable();
        btnRemoveExpired = new javax.swing.JButton();
        btnRefreshList = new javax.swing.JButton();
        FoodIncon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDesc = new javax.swing.JTextArea();
        btnCheck = new javax.swing.JButton();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Post Food Check");

        wareFoodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Food ID", "Food Name", "Quantity", "Expiry Date", "Donor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(wareFoodTable);

        btnRemoveExpired.setText("Remove Expired");
        btnRemoveExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveExpiredActionPerformed(evt);
            }
        });

        btnRefreshList.setText("Refresh List");
        btnRefreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshListActionPerformed(evt);
            }
        });

        TxtDesc.setColumns(20);
        TxtDesc.setRows(5);
        jScrollPane1.setViewportView(TxtDesc);

        btnCheck.setText("check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCheck))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FoodIncon, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRemoveExpired)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefreshList)))))
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnCheck)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodIncon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveExpired)
                    .addComponent(btnRefreshList))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        int selectedRow = wareFoodTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row first.");
            return;
        }
        WorkRequestFoodItem wrd = (WorkRequestFoodItem) wareFoodTable.getValueAt(selectedRow, 0);
        if(wrd.getFoodItem().getDecs()!=null){
            TxtDesc.setText(wrd.getFoodItem().getDecs());
        }
        if(wrd.getFoodItem().getInconPath()!=null){
            ImageIcon icon = new ImageIcon(wrd.getFoodItem().getInconPath());
            Image scaledImg = icon.getImage().getScaledInstance(250, 200, Image.SCALE_SMOOTH);
            FoodIncon.setIcon(new ImageIcon(scaledImg));
        }
        
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnRemoveExpiredActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRemoveExpiredActionPerformed
        // TODO add your handling code here:
        int rowNumber = wareFoodTable.getSelectedRow();
        if (rowNumber < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row first");
            return;
        }

        
        WorkRequestFoodItem wrd = (WorkRequestFoodItem) wareFoodTable.getValueAt(rowNumber, 0);
        if (wrd != null) {
            netWork.getWarehouseList().removeWorkRequest(wrd);
            populateTable();
        }
    }// GEN-LAST:event_btnRemoveExpiredActionPerformed

    private void btnRefreshListActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshListActionPerformed
        // TODO add your handling code here:
        populateTable();
    }// GEN-LAST:event_btnRefreshListActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FoodIncon;
    private javax.swing.JTextArea TxtDesc;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnRefreshList;
    private javax.swing.JButton btnRemoveExpired;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable wareFoodTable;
    // End of variables declaration//GEN-END:variables

    /////////////////////////// fun //////////////////
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) wareFoodTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        wareFoodTable.setRowSorter(sorter);
        model.setRowCount(0);

        if (netWork == null || netWork.getWarehouseList() == null) {
            System.out.println("Network or warehouseList is null");
            return;
        }

        WorkQueue foodQueue = netWork.getWarehouseList();
        System.out.println("Getting warehouse items: " + foodQueue.getWorkRequestList().size() + " items");

        int count = 0;
        for (WorkRequest wd : foodQueue.getWorkRequestList()) {
            if (wd instanceof WorkRequestFoodItem) {
                WorkRequestFoodItem wrf = (WorkRequestFoodItem) wd;
                count++;
                Object row[] = new Object[5];
                row[0] = count;
                row[1] = wrf.getFoodItem().getFoodName();
                row[2] = wrf.getFoodItem().getNumber();
                row[3] = wrf.getFoodItem().getExpiredDate();
                row[4] = wrf.getFoodItem().getFoodIncOrg();
                model.addRow(row);
            }
        }
    }

    private void beautify() {
        // 背景统一
        this.setBackground(new java.awt.Color(245, 242, 250));

        // 主标题样式
        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        enterpriseLabel.setForeground(new java.awt.Color(54, 33, 89)); // 深紫

        // 按钮样式统一
        javax.swing.JButton[] buttons = { btnRemoveExpired, btnRefreshList };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫按钮
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }

        // 表格样式
        wareFoodTable.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        wareFoodTable.setRowHeight(28);
        wareFoodTable.setGridColor(new java.awt.Color(200, 190, 230)); // 紫灰网格
        wareFoodTable.setForeground(new java.awt.Color(33, 33, 33));
        wareFoodTable.setSelectionBackground(new java.awt.Color(190, 170, 240));
        wareFoodTable.setSelectionForeground(java.awt.Color.WHITE);

        wareFoodTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        wareFoodTable.getTableHeader().setBackground(new java.awt.Color(230, 225, 250));
        wareFoodTable.getTableHeader().setForeground(new java.awt.Color(54, 33, 89));

        jScrollPane2.getViewport().setBackground(java.awt.Color.WHITE);
    }

}
