/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FreshCheckWorkArea;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Enterprise.BasicEnterprise;
import model.Enterprise.FreshCheckEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.PushedFoodCheckOrg;
import model.WorkQueue.WorkQueue;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestDelivery;
import model.WorkQueue.WorkRequestFoodItem;

/**
 *
 * @author sylvia
 */
public class PostFoodCheckPanel extends javax.swing.JPanel {

    /**
     * Creates new form PostFoodCheckPanel
     */
    JPanel workArea;
    FreshCheckEnterprise freshCheckEnterprise;
    PushedFoodCheckOrg pushedFoodCheckOrg;
    NetWork netWork;

    public PostFoodCheckPanel(JPanel workArea, BasicEnterprise freshCheckEnterprise, BasicOrganization organization,
            NetWork netWork) {
        this.workArea = workArea;
        this.freshCheckEnterprise = (FreshCheckEnterprise) freshCheckEnterprise;
        this.netWork = netWork;
        if (netWork == null) {
            System.err.println("Panel get NetWork==null");
        } else
            System.err.println("Panel get NetWork!=null");
        if (organization instanceof PushedFoodCheckOrg) {
            this.pushedFoodCheckOrg = (PushedFoodCheckOrg) organization;
        }
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wareFoodTable = new javax.swing.JTable();
        btnRemoveExpired = new javax.swing.JButton();
        btnRefreshList = new javax.swing.JButton();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Post Food Check");

        wareFoodTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Food ID", "Food Name", "Quantity", "Expiry Date", "Donor"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(wareFoodTable);

        btnRemoveExpired.setText("Remove Expired");
        btnRemoveExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveExpiredActionPerformed(evt);
            }
        });

        btnRefreshList.setText("Refresh List");
        btnRefreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(370, 370, 370)
                                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(130, 130, 130)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 671,
                                                                Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnRemoveExpired)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(btnRefreshList)))))
                                .addGap(199, 199, 199)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(btnRefreshList))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(btnRemoveExpired)))
                                .addGap(120, 120, 120)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveExpiredActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRemoveExpiredActionPerformed
        // TODO add your handling code here:
        int rowNumber = wareFoodTable.getSelectedRow();
        if (rowNumber < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row first");
            return;
        }

        int foodId = (int) wareFoodTable.getValueAt(rowNumber, 0);

        WorkRequestFoodItem itemToRemove = null;
        int count = 0;

        for (WorkRequest wd : netWork.getWarehouseList().getWorkRequestList()) {
            if (wd instanceof WorkRequestFoodItem) {
                count++;
                if (count == foodId) {
                    itemToRemove = (WorkRequestFoodItem) wd;
                    break;
                }
            }
        }

        // 从warehouseList中移除
        if (itemToRemove != null) {
            netWork.getWarehouseList().removeWorkRequest(itemToRemove);
            JOptionPane.showMessageDialog(this, "Food item removed successfully.");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(this, "Could not find the selected food item.");
        }
    }// GEN-LAST:event_btnRemoveExpiredActionPerformed

    private void btnRefreshListActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshListActionPerformed
        // TODO add your handling code here:
        populateTable();
    }// GEN-LAST:event_btnRefreshListActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshList;
    private javax.swing.JButton btnRemoveExpired;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable wareFoodTable;
    // End of variables declaration//GEN-END:variables

    /////////////////////////// fun //////////////////
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) wareFoodTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        wareFoodTable.setRowSorter(sorter);
        model.setRowCount(0);

        if (netWork == null || netWork.getWarehouseList() == null) {
            System.out.println("Network or warehouseList is null");
            return;
        }

        WorkQueue foodQueue = netWork.getWarehouseList();
        System.out.println("Getting warehouse items: " + foodQueue.getWorkRequestList().size() + " items");

        int count = 0;
        for (WorkRequest wd : foodQueue.getWorkRequestList()) {
            if (wd instanceof WorkRequestFoodItem) {
                WorkRequestFoodItem wrf = (WorkRequestFoodItem) wd;
                count++;
                Object row[] = new Object[5];
                row[0] = count;
                row[1] = wrf.getFoodItem().getFoodName();
                row[2] = wrf.getFoodItem().getNumber();
                row[3] = wrf.getFoodItem().getExpiredDate();
                row[4] = wrf.getFoodItem().getFoodIncOrg();
                model.addRow(row);
            }
        }
    }
}
