/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VolunteerAdminWorkAreaPanel;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.VolunteerEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.VolunteerOrg;
import model.Role.TaskManager;
import model.Role.VolunteerManager;

/**
 *
 * @author sylvia
 */
public class AddTaskManagerAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddTaskManagerAccountPanel
     */

    JPanel workArea;
    NetWork netWork;
    VolunteerOrg volunteerOrg;
    VolunteerEnterprise volunteerEnterprise;
    UserAccount account;
    TaskManagerAdminWorkPanel parentPanel;

    public AddTaskManagerAccountPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork, TaskManagerAdminWorkPanel parentPanel) {
        this.workArea = workArea;
        this.netWork = netWork;
        this.volunteerEnterprise = (VolunteerEnterprise) enterprise;
        this.volunteerOrg = (VolunteerOrg) organization;
        this.account = account;
        this.parentPanel = parentPanel;

        initComponents();
        beautify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtuserName = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblpassword = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        lblConfirmPassword = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblOrganization = new javax.swing.JLabel();
        lbluserName = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblpassword.setText("Password");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        lblConfirmPassword.setText("Email");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblOrganization.setText("Phone");

        lbluserName.setText("User Name");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Add New User - Task Manager");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(btnBack)
                                                .addGap(55, 55, 55)
                                                .addComponent(enterpriseLabel))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblpassword,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbluserName,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblConfirmPassword,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblOrganization,
                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(txtuserName)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(9, 9, 9)
                                                                .addComponent(btnSubmit))
                                                        .addComponent(txtEmail)
                                                        .addComponent(txtPhone)
                                                        .addComponent(passwordField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 155,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(470, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBack)
                                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtuserName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbluserName))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblpassword)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblConfirmPassword)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblOrganization)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(btnSubmit)
                                .addContainerGap(342, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(102, 102, 102)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(65, 65, 65)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String username = txtuserName.getText();
        String password = passwordField.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();

        if (username.isEmpty() || password.isEmpty() || email.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required. Please fill in all information.");
            return;
        }

        utils.IsMatch validator = new utils.IsMatch();
        if (!validator.isNameMatch(username)) {
            JOptionPane.showMessageDialog(this,
                    "Username should only contain letters and up to 3 spaces.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!validator.isEmailMatch(email)) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid email address.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!validator.isPhoneMatch(phone)) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid phone.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        VolunteerOrg volOrg = null;

        if (volunteerOrg != null) {
            volOrg = volunteerOrg;
        } else {
            for (BasicOrganization org : volunteerEnterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof VolunteerOrg) {
                    volOrg = (VolunteerOrg) org;
                    break;
                }
            }

            if (volOrg == null) {
                volOrg = volunteerEnterprise.createVolunteerOrg("VolunteerOrg"
                        + System.currentTimeMillis());
                JOptionPane.showMessageDialog(this, "Created new VolunteerOrg to host Task Managers");
            }
        }

        if (!volOrg.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            JOptionPane.showMessageDialog(this, "Username already exists. Please choose another username.");
            return;
        }

        VolunteerManager vm = (VolunteerManager) account.getRole();
        UserAccount newTaskManager = vm.createVolunteer(volOrg, netWork, username, password);

        newTaskManager.setRole(new TaskManager());

        newTaskManager.setEmail(email);
        newTaskManager.setPhone(phone);

        newTaskManager.setOrganization(volOrg);
        newTaskManager.setEnterprise(volunteerEnterprise);

        JOptionPane.showMessageDialog(this, "Task Manager added successfully: " + username);

        txtuserName.setText("");
        passwordField.setText("");
        txtEmail.setText("");
        txtPhone.setText("");

        if (parentPanel != null) {
            parentPanel.populateTable();
        }

    }// GEN-LAST:event_btnSubmitActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordFieldActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        parentPanel.populateTable();
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "TaskManagerAdminWorkPanel");
        workArea.revalidate();
        workArea.repaint();
    }// GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbluserName;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtuserName;

    // End of variables declaration//GEN-END:variables
    private void beautify() {
        // 背景色统一
        this.setBackground(new java.awt.Color(245, 242, 250));
        jPanel1.setBackground(new java.awt.Color(245, 242, 250));

        // 主标题样式
        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        enterpriseLabel.setForeground(new java.awt.Color(54, 33, 89)); // 深紫色标题

        // 标签字体统一
        java.awt.Font labelFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
        java.awt.Color labelColor = new java.awt.Color(80, 80, 80);
        javax.swing.JLabel[] labels = {
                lbluserName, lblpassword, lblConfirmPassword, lblOrganization
        };
        for (javax.swing.JLabel label : labels) {
            label.setFont(labelFont);
            label.setForeground(labelColor);
        }

        // 文本框样式
        javax.swing.JTextField[] textFields = { txtuserName, txtEmail, txtPhone };
        for (javax.swing.JTextField field : textFields) {
            field.setFont(labelFont);
            field.setBackground(java.awt.Color.WHITE);
            field.setForeground(new java.awt.Color(40, 40, 40));
            field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));
        }

        // 密码框样式
        passwordField.setFont(labelFont);
        passwordField.setBackground(java.awt.Color.WHITE);
        passwordField.setForeground(new java.awt.Color(40, 40, 40));
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 150, 200)));

        // 按钮样式
        javax.swing.JButton[] buttons = { btnBack, btnSubmit };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(labelFont);
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫色
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }
    }

}
