/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VolunteerAdminWorkAreaPanel;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.VolunteerEnterprise;
import model.FoodItem.FoodItem;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.DriverOrg;
import model.Organization.VolunteerOrg;
import model.Role.Deliver;
import model.WorkQueue.WorkQueue;
import model.WorkQueue.WorkRequest;
import model.WorkQueue.WorkRequestFoodItem;

/**
 *
 * @author sylvia
 */
public class DriverAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerSchedulerWorkPanel
     */    
    JPanel workArea;
    NetWork netWork;
    VolunteerOrg volunteerOrg;
    VolunteerEnterprise volunteerEnterprise;
    UserAccount account;
    DriverAdminWorkAreaPanel parentPanel;
    
    public DriverAdminWorkAreaPanel(JPanel workArea, UserAccount account, BasicOrganization organization, BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.netWork = netWork;
        this.volunteerEnterprise = (VolunteerEnterprise) enterprise;
        this.volunteerOrg = (VolunteerOrg) organization;
        this.account = account;
        
        lblEnterprise.setText("Enterprise: " + enterprise.getName());
        
        populateTable();

        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDriver = new javax.swing.JTable();
        btnAddDriver = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Drivers Management");

        tblDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Driver ID", "Name", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDriver);

        btnAddDriver.setText("Add");
        btnAddDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDriverActionPerformed(evt);
            }
        });

        lblEnterprise.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise: < >");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterprise)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(103, 103, 103)
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnAddDriver)
                .addGap(169, 169, 169)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnterprise)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDriver)
                    .addComponent(btnDelete))
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        workArea.remove(this);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.show(workArea,"VolunteerAdminStartPoint");
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnAddDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDriverActionPerformed
        // TODO add your handling code here:
                
        CardLayout layout = (CardLayout) workArea.getLayout();
        workArea.add("AddDriverAccountPanel", new AddDriverAccountPanel(workArea, account, volunteerOrg, volunteerEnterprise, netWork, parentPanel));
        layout.show(workArea,"AddDriverAccountPanel");
        
    }//GEN-LAST:event_btnAddDriverActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDriver.getSelectedRow();
        
        if (selectedRow <0){
            JOptionPane.showMessageDialog(this, "Please select an account to delete", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
        
        String username = (String) tblDriver.getValueAt(selectedRow, 0);
        
        UserAccount toRemove = null;
        
        DriverOrg driverOrg = null;

        for (BasicEnterprise en : netWork.getEnterpriseDirectory().getEnterprises()) {
            if (en instanceof VolunteerEnterprise) {
                VolunteerEnterprise volunteerEnterprise = (VolunteerEnterprise) en;
                for (BasicOrganization org : volunteerEnterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof DriverOrg) {
                        driverOrg = (DriverOrg) org;
                        break;
                    }
                }
            }
            if (driverOrg != null) {
                break; 
            }
        }
      
        for (UserAccount ua: driverOrg.getUserAccountDirectory().getUserAccountList() ){
            if (ua.getUsername().equals(username)){
                toRemove = ua;
                break;
            }
        }
      
        if (toRemove != null){
            driverOrg.getUserAccountDirectory().getUserAccountList().remove(toRemove);
            JOptionPane.showMessageDialog(this, "User deleted successfully.");
            populateTable();
        }        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddDriver;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JTable tblDriver;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblDriver.getModel();
        model.setRowCount(0);
       
        for (UserAccount ua : volunteerOrg.getUserAccountDirectory().getUserAccountList()){
           if (ua.getRole() instanceof Deliver){     
            
            Deliver deliver = (Deliver) ua.getRole();   
            
            Object[] row = new Object[3];
            row[0] = deliver.getID();
            row[1] = ua.getUsername();
            row[1] = deliver.getContact();
            model.addRow(row);
           } 
        }
        
    }
}
