/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VolunteerAdminWorkAreaPanel;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.VolunteerEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.DriverOrg;
import model.Organization.VolunteerOrg;
import model.Role.Deliver;
import utils.PanelUtils;

/**
 *
 * @author sylvia
 */
public class DriverAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerSchedulerWorkPanel
     */
    JPanel workArea;
    NetWork netWork;
    VolunteerOrg volunteerOrg;
    VolunteerEnterprise volunteerEnterprise;
    UserAccount account;
    DriverAdminWorkAreaPanel parentPanel;

    public DriverAdminWorkAreaPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.netWork = netWork;
        this.volunteerEnterprise = (VolunteerEnterprise) enterprise;
        this.volunteerOrg = (VolunteerOrg) organization;
        this.account = account;
        initComponents();

        lblEnterprise.setText("Enterprise: " + enterprise.getName());

        populateTable();
        beautify();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDriver = new javax.swing.JTable();
        btnAddDriver = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Drivers Management");

        tblDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Driver ID", "Name", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDriver);

        btnAddDriver.setText("Add");
        btnAddDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDriverActionPerformed(evt);
            }
        });

        lblEnterprise.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise: < >");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddDriver)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(202, 202, 202)
                        .addComponent(btnDelete))
                    .addComponent(lblEnterprise)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(103, 103, 103)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblEnterprise)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDriver)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addContainerGap(415, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDriver.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an account to delete", "Warning",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        UserAccount ua = (UserAccount) tblDriver.getValueAt(selectedRow, 1);
        AddDriverAccountPanel addDriverAccountPanel = new AddDriverAccountPanel(workArea, account, volunteerOrg, volunteerEnterprise, netWork, parentPanel, ua);
        PanelUtils.addOrReplacePanel(workArea, "AddDriverAccountPanel", addDriverAccountPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "AddDriverAccountPanel");
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backJButtonActionPerformed

        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "VolunteerAdminStartPoint");
        workArea.revalidate();
        workArea.repaint();
    }// GEN-LAST:event_backJButtonActionPerformed

    private void btnAddDriverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddDriverActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) workArea.getLayout();
        workArea.add("AddDriverAccountPanel",
                new AddDriverAccountPanel(workArea, account, volunteerOrg, volunteerEnterprise, netWork, parentPanel,null));
        layout.show(workArea, "AddDriverAccountPanel");
        workArea.revalidate();
        workArea.repaint();

    }// GEN-LAST:event_btnAddDriverActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblDriver.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an account to delete", "Warning",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String accountUuid = (String) tblDriver.getValueAt(selectedRow, 0); // 获取ID

        UserAccount toRemove = null;
        DriverOrg driverOrg = null;

        for (BasicEnterprise en : netWork.getEnterpriseDirectory().getEnterprises()) {
            if (en instanceof VolunteerEnterprise) {
                VolunteerEnterprise volunteerEnterprise = (VolunteerEnterprise) en;
                for (BasicOrganization org : volunteerEnterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof DriverOrg) {
                        driverOrg = (DriverOrg) org;
                        break;
                    }
                }

            }
            if (driverOrg != null) {
                break;
            }
        }

        if (driverOrg != null) {
            // 用accountUuid查找用户，如果后面改了ID的生成方式，记得改这里，要不然可能报错！
            for (UserAccount ua : driverOrg.getUserAccountDirectory().getUserAccountList()) {
                if (ua.getAccountUuid() != null && ua.getAccountUuid().equals(accountUuid)) {

                    toRemove = ua;
                    break;
                }
            }

            if (toRemove != null) {
                driverOrg.getUserAccountDirectory().getUserAccountList().remove(toRemove);
                JOptionPane.showMessageDialog(this, "User deleted successfully.");
                populateTable();

            } else {
                JOptionPane.showMessageDialog(this, "Could not find user to delete.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Could not find driver organization.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddDriver;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JTable tblDriver;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblDriver.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblDriver.setRowSorter(sorter);
        model.setRowCount(0);

        if (volunteerOrg == null) {
            for (BasicOrganization org : volunteerEnterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof DriverOrg) {
                    DriverOrg driverOrg = (DriverOrg) org;

                    for (UserAccount ua : driverOrg.getUserAccountDirectory().getUserAccountList()) {
                        if (ua.getRole() instanceof Deliver) {
                            Deliver deliver = (Deliver) ua.getRole();

                            Object[] row = new Object[3];
                            row[0] = ua.getAccountUuid() != null ? ua.getAccountUuid() : "N/A";
                            row[1] = ua;
                            row[2] = ua.getPhone() != null ? ua.getPhone() : "N/A";
                            model.addRow(row);
                        }
                    }
                }
            }
        } else {
            for (UserAccount ua : volunteerOrg.getUserAccountDirectory().getUserAccountList()) {
                if (ua.getRole() instanceof Deliver) {
                    Deliver deliver = (Deliver) ua.getRole();

                    Object[] row = new Object[3];
                    row[0] = ua.getAccountUuid() != null ? ua.getAccountUuid() : "N/A";
                    row[1] = ua;
                    row[2] = ua.getPhone() != null ? ua.getPhone() : "N/A";
                    model.addRow(row);
                }
            }
        }
    }

    private void beautify() {
        // 背景统一
        this.setBackground(new java.awt.Color(245, 242, 250));

        // 主标题与企业标签样式
        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        enterpriseLabel.setForeground(new java.awt.Color(54, 33, 89)); // 深紫

        lblEnterprise.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        lblEnterprise.setForeground(new java.awt.Color(80, 80, 80)); // 深灰

        // 按钮样式
        javax.swing.JButton[] buttons = { backJButton, btnAddDriver, btnDelete,btnUpdate };
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
            btn.setBackground(new java.awt.Color(103, 58, 183)); // 深紫按钮
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        }

        // 表格样式
        tblDriver.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        tblDriver.setRowHeight(28);
        tblDriver.setGridColor(new java.awt.Color(200, 190, 230)); // 紫灰网格
        tblDriver.setForeground(new java.awt.Color(33, 33, 33));
        tblDriver.setSelectionBackground(new java.awt.Color(190, 170, 240));
        tblDriver.setSelectionForeground(java.awt.Color.WHITE);

        tblDriver.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        tblDriver.getTableHeader().setBackground(new java.awt.Color(230, 225, 250));
        tblDriver.getTableHeader().setForeground(new java.awt.Color(54, 33, 89));

        jScrollPane3.getViewport().setBackground(java.awt.Color.WHITE);
    }

}
