/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VolunteerAdminWorkAreaPanel;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.VolunteerEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.VolunteerOrg;
import model.Role.TaskManager;

/**
 *
 * @author sylvia
 */
public class TaskManagerAdminWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaskManagerAdminWorkPanel
     */

    JPanel workArea;
    NetWork netWork;
    VolunteerOrg volunteerOrg;
    VolunteerEnterprise volunteerEnterprise;
    UserAccount account;
    TaskManagerAdminWorkPanel parentPanel;

    public TaskManagerAdminWorkPanel(JPanel workArea, UserAccount account, BasicOrganization organization,
            BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.netWork = netWork;
        this.volunteerEnterprise = (VolunteerEnterprise) enterprise;
        this.volunteerOrg = (VolunteerOrg) organization;
        this.account = account;
        initComponents();
        lblEnterprise.setText("Enterprise: " + enterprise.getName());
        this.parentPanel = this;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaskManager = new javax.swing.JTable();
        btnAddTaskManager = new javax.swing.JButton();
        btnDeleteTaskManager = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();

        tblTaskManager.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null },
                        { null, null, null },
                        { null, null, null },
                        { null, null, null }
                },
                new String[] {
                        "Task Manager ID", "Name", "Contact"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTaskManager);

        btnAddTaskManager.setText("Add");
        btnAddTaskManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskManagerActionPerformed(evt);
            }
        });

        btnDeleteTaskManager.setText("Delete");
        btnDeleteTaskManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTaskManagerActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Task Manager Management");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        lblEnterprise.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise: < >");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEnterprise)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(131, 131, 131)
                                                .addComponent(btnAddTaskManager)
                                                .addGap(183, 183, 183)
                                                .addComponent(btnDeleteTaskManager))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(backJButton)
                                                .addGap(91, 91, 91)
                                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(409, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblEnterprise)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(backJButton))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDeleteTaskManager)
                                        .addComponent(btnAddTaskManager))
                                .addContainerGap(397, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTaskManagerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddTaskManagerActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) workArea.getLayout();
        workArea.add("AddTaskManagerAccountPanel", new AddTaskManagerAccountPanel(workArea, account, volunteerOrg,
                volunteerEnterprise, netWork, parentPanel));
        layout.show(workArea, "AddTaskManagerAccountPanel");
        workArea.revalidate();
        workArea.repaint();

    }// GEN-LAST:event_btnAddTaskManagerActionPerformed

    private void btnDeleteTaskManagerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteTaskManagerActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblTaskManager.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an account to delete", "Warning",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String accountUuid = (String) tblTaskManager.getValueAt(selectedRow, 0);
        String username = (String) tblTaskManager.getValueAt(selectedRow, 1);

        UserAccount toRemove = null;
        VolunteerOrg targetOrg = null;

        if (volunteerOrg != null) {
            targetOrg = volunteerOrg;
        } else {

            for (BasicOrganization org : volunteerEnterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof VolunteerOrg) {
                    VolunteerOrg volOrg = (VolunteerOrg) org;
                    for (UserAccount ua : volOrg.getUserAccountDirectory().getUserAccountList()) {
                        // 用accountUuid查找用户，如果后面改了ID的生成方式，记得改这里，要不然可能报错！
                        if (ua.getAccountUuid() != null && ua.getAccountUuid().equals(accountUuid)) {
                            toRemove = ua;
                            targetOrg = volOrg;
                            break;
                        } else if (ua.getUsername().equals(username)) {
                            toRemove = ua;
                            targetOrg = volOrg;
                            break;
                        }
                    }
                    if (toRemove != null)
                        break;
                }
            }
        }

        if (toRemove != null && targetOrg != null) {
            targetOrg.getUserAccountDirectory().getUserAccountList().remove(toRemove);
            JOptionPane.showMessageDialog(this, "User deleted successfully.");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(this, "Could not find user to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backJButtonActionPerformed

        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "VolunteerAdminStartPoint");
        workArea.revalidate();
        workArea.repaint();
    }// GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddTaskManager;
    private javax.swing.JButton btnDeleteTaskManager;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JTable tblTaskManager;
    // End of variables declaration//GEN-END:variables

    void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblTaskManager.getModel();
        model.setRowCount(0);

        if (volunteerOrg == null) {

            for (BasicOrganization org : volunteerEnterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof VolunteerOrg) {
                    VolunteerOrg volOrg = (VolunteerOrg) org;

                    for (UserAccount ua : volOrg.getUserAccountDirectory().getUserAccountList()) {
                        if (ua.getRole() instanceof TaskManager) {
                            TaskManager tm = (TaskManager) ua.getRole();

                            Object[] row = new Object[3];
                            row[0] = ua.getAccountUuid() != null ? ua.getAccountUuid() : "N/A";
                            row[1] = ua.getUsername();
                            row[2] = ua.getPhone() != null ? ua.getPhone() : "N/A";
                            model.addRow(row);
                        }
                    }
                }
            }
        } else {
            for (UserAccount ua : volunteerOrg.getUserAccountDirectory().getUserAccountList()) {
                if (ua.getRole() instanceof TaskManager) {
                    TaskManager tm = (TaskManager) ua.getRole();

                    Object[] row = new Object[3];
                    row[0] = ua.getAccountUuid() != null ? ua.getAccountUuid() : "N/A";
                    row[1] = ua.getUsername();
                    row[2] = ua.getPhone() != null ? ua.getPhone() : "N/A";
                    model.addRow(row);
                }
            }
        }

    }
}
