/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VolunteerAdminWorkAreaPanel;


import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.VolunteerEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.VolunteerOrg;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Account.UserAccount;
import model.Enterprise.BasicEnterprise;
import model.Enterprise.FoodEnterprise;
import model.Enterprise.VolunteerEnterprise;
import model.NetWork.NetWork;
import model.Organization.BasicOrganization;
import model.Organization.DriverOrg;
import model.Organization.FoodIncOrg;
import model.Organization.VolunteerOrg;
import ui.FoodProviderWorkArea.MyDonationTablePanel;
/**
 *
 * @author yuewu
 */
public class VolunteerAdminStartPoint extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerAdminStartPoint
     */
    
    JPanel workArea;
    NetWork netWork;
    VolunteerOrg volunteerOrg;
    VolunteerEnterprise volunteerEnterprise;
    UserAccount account;
    public VolunteerAdminStartPoint(JPanel workArea, UserAccount account, BasicOrganization organization, BasicEnterprise enterprise, NetWork netWork) {
        this.workArea = workArea;
        this.netWork = netWork;
        this.volunteerEnterprise = (VolunteerEnterprise) enterprise;
        this.volunteerOrg = (VolunteerOrg) organization;
        this.account = account;
        
        initComponents();
        System.out.println("VolunteerAdminStartPoint构造函数 - account: " + (account != null ? account.getUsername() : "null"));
        System.out.println("VolunteerAdminStartPoint构造函数 - enterprise: " + (enterprise != null ? enterprise.getName() : "null"));
        System.out.println("VolunteerAdminStartPoint构造函数 - organization: " + (organization != null ? organization.getName() : "null"));

        lblWelcome.setText("Welcome, " + account.getUsername() + " !");
        lblEnterprise.setText("Enterprise: " + enterprise.getName());
        if (organization != null && organization instanceof VolunteerOrg) {
        this.volunteerOrg = (VolunteerOrg) organization;
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        btnManageDriver = new javax.swing.JButton();
        btnManageTaskManager = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 102));

        lblWelcome.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblWelcome.setText("Welcome, <value>");

        lblEnterprise.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise: < >");

        btnManageDriver.setText("Manage Drivers");
        btnManageDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDriverActionPerformed(evt);
            }
        });

        btnManageTaskManager.setText("Manage Task Managers");
        btnManageTaskManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTaskManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnterprise))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageTaskManager)
                            .addComponent(btnManageDriver))))
                .addContainerGap(682, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageDriver, btnManageTaskManager});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(lblEnterprise))
                .addGap(67, 67, 67)
                .addComponent(btnManageDriver)
                .addGap(35, 35, 35)
                .addComponent(btnManageTaskManager)
                .addContainerGap(537, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDriverActionPerformed
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout) workArea.getLayout();
        workArea.add("DriverAdminWorkAreaPanel", new DriverAdminWorkAreaPanel(workArea, account, volunteerOrg, volunteerEnterprise, netWork));
        layout.show(workArea,"DriverAdminWorkAreaPanel");
                
    }//GEN-LAST:event_btnManageDriverActionPerformed

    private void btnManageTaskManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTaskManagerActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) workArea.getLayout();
        workArea.add("TaskManagerAdminWorkPanel", new TaskManagerAdminWorkPanel(workArea, account, volunteerOrg, volunteerEnterprise, netWork));
        layout.show(workArea,"TaskManagerAdminWorkPanel");
        

    }//GEN-LAST:event_btnManageTaskManagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDriver;
    private javax.swing.JButton btnManageTaskManager;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
